
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package calc.parser;

/** CUP generated class containing symbol constants. */
public class Lang2ParserSym {
  /* terminals */
  public static final int FLOAT_LIT = 19;
  public static final int CHAR_LIT = 20;
  public static final int LBRACKET = 25;
  public static final int TYCHAR = 13;
  public static final int LPAREN = 23;
  public static final int SEMI = 30;
  public static final int MINUS = 44;
  public static final int RPAREN = 24;
  public static final int DATA = 2;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int LT = 39;
  public static final int TYBOOL = 14;
  public static final int COMMA = 29;
  public static final int DIV = 46;
  public static final int PLUS = 43;
  public static final int ASSIGN = 35;
  public static final int IF = 4;
  public static final int DOT = 32;
  public static final int ID = 21;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int TYPE_AND = 37;
  public static final int RBRACKET = 26;
  public static final int TRUE = 16;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int NULL = 10;
  public static final int MOD = 47;
  public static final int NEQ = 42;
  public static final int VOID = 11;
  public static final int EQ = 41;
  public static final int TYID = 22;
  public static final int ITERATE = 3;
  public static final int TIMES = 45;
  public static final int ARROW = 34;
  public static final int COLON = 31;
  public static final int LBRACE = 27;
  public static final int ELSE = 5;
  public static final int READ = 9;
  public static final int TYINT = 12;
  public static final int DCOLON = 33;
  public static final int RBRACE = 28;
  public static final int FALSE = 17;
  public static final int TYFLOAT = 15;
  public static final int GT = 40;
  public static final int INT_LIT = 18;
  public static final int PRINT = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DATA",
  "ITERATE",
  "IF",
  "ELSE",
  "RETURN",
  "NEW",
  "PRINT",
  "READ",
  "NULL",
  "VOID",
  "TYINT",
  "TYCHAR",
  "TYBOOL",
  "TYFLOAT",
  "TRUE",
  "FALSE",
  "INT_LIT",
  "FLOAT_LIT",
  "CHAR_LIT",
  "ID",
  "TYID",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMI",
  "COLON",
  "DOT",
  "DCOLON",
  "ARROW",
  "ASSIGN",
  "AND",
  "TYPE_AND",
  "NOT",
  "LT",
  "GT",
  "EQ",
  "NEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD"
  };
}

