
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package calc.parser;

import java_cup.runtime.*;
import calc.nodes.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Lang2Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Lang2ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public Lang2Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Lang2Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Lang2Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\110\000\002\002\004\000\002\002\003\000\002\002" +
    "\002\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\005\007\000\002\007\004\000" +
    "\002\007\002\000\002\010\006\000\002\006\007\000\002" +
    "\011\004\000\002\011\002\000\002\012\005\000\002\012" +
    "\003\000\002\013\005\000\002\013\003\000\002\014\005" +
    "\000\002\014\003\000\002\015\003\000\002\015\003\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\015\003\000\002\016\005\000\002\017\004\000\002\017" +
    "\002\000\002\020\007\000\002\020\011\000\002\020\007" +
    "\000\002\020\011\000\002\020\007\000\002\020\005\000" +
    "\002\020\005\000\002\020\004\000\002\020\006\000\002" +
    "\020\004\000\002\020\003\000\002\020\003\000\002\022" +
    "\005\000\002\022\003\000\002\021\005\000\002\021\005" +
    "\000\002\021\005\000\002\021\005\000\002\021\005\000" +
    "\002\021\005\000\002\021\005\000\002\021\005\000\002" +
    "\021\005\000\002\021\004\000\002\021\005\000\002\021" +
    "\004\000\002\021\007\000\002\021\003\000\002\021\003" +
    "\000\002\021\003\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\021\003\000\002\021\006\000\002" +
    "\021\005\000\002\023\005\000\002\023\003\000\002\024" +
    "\003\000\002\024\006\000\002\024\005\000\002\024\011" +
    "\000\002\024\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\223\000\010\002\uffff\004\006\027\004\001\002\000" +
    "\006\027\ufff4\043\ufff4\001\002\000\010\002\ufffd\004\006" +
    "\027\004\001\002\000\004\030\014\001\002\000\010\002" +
    "\ufffc\004\ufffc\027\ufffc\001\002\000\004\002\000\001\002" +
    "\000\004\002\013\001\002\000\010\002\ufffb\004\ufffb\027" +
    "\ufffb\001\002\000\004\002\001\001\002\000\004\035\015" +
    "\001\002\000\006\027\016\036\ufff8\001\002\000\004\041" +
    "\023\001\002\000\004\036\022\001\002\000\006\027\016" +
    "\036\ufff8\001\002\000\004\036\ufff9\001\002\000\010\002" +
    "\ufffa\004\ufffa\027\ufffa\001\002\000\016\015\032\016\026" +
    "\017\033\020\030\021\024\030\031\001\002\000\044\032" +
    "\uffea\033\uffea\034\uffea\035\uffea\037\uffea\040\uffea\044\uffea" +
    "\046\uffea\047\uffea\051\uffea\053\uffea\054\uffea\055\uffea\056" +
    "\uffea\057\uffea\060\uffea\061\uffea\001\002\000\004\040\036" +
    "\001\002\000\044\032\uffed\033\uffed\034\uffed\035\uffed\037" +
    "\uffed\040\uffed\044\uffed\046\uffed\047\uffed\051\uffed\053\uffed" +
    "\054\uffed\055\uffed\056\uffed\057\uffed\060\uffed\061\uffed\001" +
    "\002\000\044\032\uffee\033\034\034\uffee\035\uffee\037\uffee" +
    "\040\uffee\044\uffee\046\uffee\047\uffee\051\uffee\053\uffee\054" +
    "\uffee\055\uffee\056\uffee\057\uffee\060\uffee\061\uffee\001\002" +
    "\000\044\032\uffeb\033\uffeb\034\uffeb\035\uffeb\037\uffeb\040" +
    "\uffeb\044\uffeb\046\uffeb\047\uffeb\051\uffeb\053\uffeb\054\uffeb" +
    "\055\uffeb\056\uffeb\057\uffeb\060\uffeb\061\uffeb\001\002\000" +
    "\044\032\uffe8\033\uffe8\034\uffe8\035\uffe8\037\uffe8\040\uffe8" +
    "\044\uffe8\046\uffe8\047\uffe8\051\uffe8\053\uffe8\054\uffe8\055" +
    "\uffe8\056\uffe8\057\uffe8\060\uffe8\061\uffe8\001\002\000\044" +
    "\032\uffe9\033\uffe9\034\uffe9\035\uffe9\037\uffe9\040\uffe9\044" +
    "\uffe9\046\uffe9\047\uffe9\051\uffe9\053\uffe9\054\uffe9\055\uffe9" +
    "\056\uffe9\057\uffe9\060\uffe9\061\uffe9\001\002\000\044\032" +
    "\uffec\033\uffec\034\uffec\035\uffec\037\uffec\040\uffec\044\uffec" +
    "\046\uffec\047\uffec\051\uffec\053\uffec\054\uffec\055\uffec\056" +
    "\uffec\057\uffec\060\uffec\061\uffec\001\002\000\004\034\035" +
    "\001\002\000\044\032\uffef\033\uffef\034\uffef\035\uffef\037" +
    "\uffef\040\uffef\044\uffef\046\uffef\047\uffef\051\uffef\053\uffef" +
    "\054\uffef\055\uffef\056\uffef\057\uffef\060\uffef\061\uffef\001" +
    "\002\000\006\027\ufff7\036\ufff7\001\002\000\004\002\ufffe" +
    "\001\002\000\006\027\041\043\042\001\002\000\006\027" +
    "\ufff5\043\ufff5\001\002\000\016\015\032\016\026\017\033" +
    "\020\030\021\024\030\031\001\002\000\010\035\ufff0\044" +
    "\221\047\222\001\002\000\004\035\ufff2\001\002\000\004" +
    "\035\046\001\002\000\046\005\056\006\060\010\055\011" +
    "\070\012\065\013\050\014\072\022\057\023\064\024\067" +
    "\025\071\026\074\027\063\031\061\035\046\036\uffe5\040" +
    "\053\050\054\001\002\000\010\002\ufff6\004\ufff6\027\ufff6" +
    "\001\002\000\006\027\205\031\206\001\002\000\004\036" +
    "\203\001\002\000\026\040\202\046\103\051\113\053\110" +
    "\054\106\055\107\056\102\057\112\060\111\061\104\001" +
    "\002\000\050\005\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9" +
    "\012\uffd9\013\uffd9\014\uffd9\022\uffd9\023\uffd9\024\uffd9\025" +
    "\uffd9\026\uffd9\027\uffd9\031\uffd9\035\uffd9\036\uffd9\040\uffd9" +
    "\050\uffd9\001\002\000\026\011\070\014\072\022\057\023" +
    "\064\024\067\025\071\026\074\027\063\031\061\050\054" +
    "\001\002\000\030\011\070\014\072\022\057\023\064\024" +
    "\067\025\071\026\074\027\063\031\061\040\176\050\054" +
    "\001\002\000\004\031\166\001\002\000\034\032\uffc5\034" +
    "\uffc5\037\uffc5\040\uffc5\046\uffc5\051\uffc5\053\uffc5\054\uffc5" +
    "\055\uffc5\056\uffc5\057\uffc5\060\uffc5\061\uffc5\001\002\000" +
    "\004\031\160\001\002\000\026\011\070\014\072\022\057" +
    "\023\064\024\067\025\071\026\074\027\063\031\061\050" +
    "\054\001\002\000\050\005\uffda\006\uffda\007\uffda\010\uffda" +
    "\011\uffda\012\uffda\013\uffda\014\uffda\022\uffda\023\uffda\024" +
    "\uffda\025\uffda\026\uffda\027\uffda\031\uffda\035\uffda\036\uffda" +
    "\040\uffda\050\uffda\001\002\000\044\031\141\032\uffbe\033" +
    "\uffbe\034\uffbe\037\uffbe\040\uffbe\042\uffbe\045\uffbe\046\uffbe" +
    "\051\uffbe\053\uffbe\054\uffbe\055\uffbe\056\uffbe\057\uffbe\060" +
    "\uffbe\061\uffbe\001\002\000\034\032\uffc4\034\uffc4\037\uffc4" +
    "\040\uffc4\046\uffc4\051\uffc4\053\uffc4\054\uffc4\055\uffc4\056" +
    "\uffc4\057\uffc4\060\uffc4\061\uffc4\001\002\000\004\031\135" +
    "\001\002\000\046\005\056\006\060\010\055\011\070\012" +
    "\065\013\050\014\072\022\057\023\064\024\067\025\071" +
    "\026\074\027\063\031\061\035\046\036\uffe5\040\053\050" +
    "\054\001\002\000\034\032\uffc8\034\uffc8\037\uffc8\040\uffc8" +
    "\046\uffc8\051\uffc8\053\uffc8\054\uffc8\055\uffc8\056\uffc8\057" +
    "\uffc8\060\uffc8\061\uffc8\001\002\000\016\015\032\016\026" +
    "\017\033\020\030\021\024\030\031\001\002\000\034\032" +
    "\uffc7\034\uffc7\037\uffc7\040\uffc7\046\uffc7\051\uffc7\053\uffc7" +
    "\054\uffc7\055\uffc7\056\uffc7\057\uffc7\060\uffc7\061\uffc7\001" +
    "\002\000\034\032\uffc9\034\uffc9\037\uffc9\040\uffc9\046\uffc9" +
    "\051\uffc9\053\uffc9\054\uffc9\055\uffc9\056\uffc9\057\uffc9\060" +
    "\uffc9\061\uffc9\001\002\000\034\033\075\040\uffc3\042\076" +
    "\045\077\046\uffc3\051\uffc3\053\uffc3\054\uffc3\055\uffc3\056" +
    "\uffc3\057\uffc3\060\uffc3\061\uffc3\001\002\000\034\032\uffc6" +
    "\034\uffc6\037\uffc6\040\uffc6\046\uffc6\051\uffc6\053\uffc6\054" +
    "\uffc6\055\uffc6\056\uffc6\057\uffc6\060\uffc6\061\uffc6\001\002" +
    "\000\026\011\070\014\072\022\057\023\064\024\067\025" +
    "\071\026\074\027\063\031\061\050\054\001\002\000\004" +
    "\027\125\001\002\000\026\011\070\014\072\022\057\023" +
    "\064\024\067\025\071\026\074\027\063\031\061\050\054" +
    "\001\002\000\026\040\105\046\103\051\113\053\110\054" +
    "\106\055\107\056\102\057\112\060\111\061\104\001\002" +
    "\000\040\032\uffc3\033\075\034\uffc3\037\uffc3\040\uffc3\042" +
    "\076\046\uffc3\051\uffc3\053\uffc3\054\uffc3\055\uffc3\056\uffc3" +
    "\057\uffc3\060\uffc3\061\uffc3\001\002\000\026\011\070\014" +
    "\072\022\057\023\064\024\067\025\071\026\074\027\063" +
    "\031\061\050\054\001\002\000\026\011\070\014\072\022" +
    "\057\023\064\024\067\025\071\026\074\027\063\031\061" +
    "\050\054\001\002\000\026\011\070\014\072\022\057\023" +
    "\064\024\067\025\071\026\074\027\063\031\061\050\054" +
    "\001\002\000\050\005\uffdc\006\uffdc\007\uffdc\010\uffdc\011" +
    "\uffdc\012\uffdc\013\uffdc\014\uffdc\022\uffdc\023\uffdc\024\uffdc" +
    "\025\uffdc\026\uffdc\027\uffdc\031\uffdc\035\uffdc\036\uffdc\040" +
    "\uffdc\050\uffdc\001\002\000\026\011\070\014\072\022\057" +
    "\023\064\024\067\025\071\026\074\027\063\031\061\050" +
    "\054\001\002\000\026\011\070\014\072\022\057\023\064" +
    "\024\067\025\071\026\074\027\063\031\061\050\054\001" +
    "\002\000\026\011\070\014\072\022\057\023\064\024\067" +
    "\025\071\026\074\027\063\031\061\050\054\001\002\000" +
    "\026\011\070\014\072\022\057\023\064\024\067\025\071" +
    "\026\074\027\063\031\061\050\054\001\002\000\026\011" +
    "\070\014\072\022\057\023\064\024\067\025\071\026\074" +
    "\027\063\031\061\050\054\001\002\000\026\011\070\014" +
    "\072\022\057\023\064\024\067\025\071\026\074\027\063" +
    "\031\061\050\054\001\002\000\026\032\uffce\034\uffce\037" +
    "\uffce\040\uffce\046\uffce\055\107\056\102\057\112\060\111" +
    "\061\104\001\002\000\034\032\uffd4\034\uffd4\037\uffd4\040" +
    "\uffd4\046\uffd4\051\uffd4\053\uffd4\054\uffd4\055\uffd4\056\uffd4" +
    "\057\uffd4\060\uffd4\061\uffd4\001\002\000\034\032\uffd3\034" +
    "\uffd3\037\uffd3\040\uffd3\046\uffd3\051\uffd3\053\uffd3\054\uffd3" +
    "\055\uffd3\056\uffd3\057\uffd3\060\uffd3\061\uffd3\001\002\000" +
    "\026\032\uffd0\034\uffd0\037\uffd0\040\uffd0\046\uffd0\055\107" +
    "\056\102\057\112\060\111\061\104\001\002\000\034\032" +
    "\uffd6\034\uffd6\037\uffd6\040\uffd6\046\uffd6\051\uffd6\053\uffd6" +
    "\054\uffd6\055\uffd6\056\uffd6\057\112\060\111\061\104\001" +
    "\002\000\026\032\uffcf\034\uffcf\037\uffcf\040\uffcf\046\uffcf" +
    "\055\107\056\102\057\112\060\111\061\104\001\002\000" +
    "\034\032\uffd2\034\uffd2\037\uffd2\040\uffd2\046\uffd2\051\uffd2" +
    "\053\uffd2\054\uffd2\055\uffd2\056\uffd2\057\uffd2\060\uffd2\061" +
    "\uffd2\001\002\000\034\032\uffd1\034\uffd1\037\uffd1\040\uffd1" +
    "\046\uffd1\051\113\053\110\054\106\055\107\056\102\057" +
    "\112\060\111\061\104\001\002\000\034\032\uffd5\034\uffd5" +
    "\037\uffd5\040\uffd5\046\uffd5\051\uffd5\053\uffd5\054\uffd5\055" +
    "\uffd5\056\uffd5\057\112\060\111\061\104\001\002\000\044" +
    "\032\uffbc\033\uffbc\034\uffbc\037\uffbc\040\uffbc\042\uffbc\045" +
    "\uffbc\046\uffbc\051\uffbc\052\uffbc\053\uffbc\054\uffbc\055\uffbc" +
    "\056\uffbc\057\uffbc\060\uffbc\061\uffbc\001\002\000\026\034" +
    "\127\046\103\051\113\053\110\054\106\055\107\056\102" +
    "\057\112\060\111\061\104\001\002\000\044\032\uffbd\033" +
    "\uffbd\034\uffbd\037\uffbd\040\uffbd\042\uffbd\045\uffbd\046\uffbd" +
    "\051\uffbd\052\uffbd\053\uffbd\054\uffbd\055\uffbd\056\uffbd\057" +
    "\uffbd\060\uffbd\061\uffbd\001\002\000\036\032\uffcb\033\131" +
    "\034\uffcb\037\uffcb\040\uffcb\046\uffcb\051\uffcb\053\uffcb\054" +
    "\uffcb\055\uffcb\056\uffcb\057\uffcb\060\uffcb\061\uffcb\001\002" +
    "\000\026\011\070\014\072\022\057\023\064\024\067\025" +
    "\071\026\074\027\063\031\061\050\054\001\002\000\026" +
    "\034\133\046\103\051\113\053\110\054\106\055\107\056" +
    "\102\057\112\060\111\061\104\001\002\000\034\032\uffca" +
    "\034\uffca\037\uffca\040\uffca\046\uffca\051\uffca\053\uffca\054" +
    "\uffca\055\uffca\056\uffca\057\uffca\060\uffca\061\uffca\001\002" +
    "\000\004\036\uffe6\001\002\000\026\011\070\014\072\022" +
    "\057\023\064\024\067\025\071\026\074\027\063\031\061" +
    "\050\054\001\002\000\026\032\137\046\103\051\113\053" +
    "\110\054\106\055\107\056\102\057\112\060\111\061\104" +
    "\001\002\000\004\040\140\001\002\000\050\005\uffe0\006" +
    "\uffe0\007\uffe0\010\uffe0\011\uffe0\012\uffe0\013\uffe0\014\uffe0" +
    "\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\031" +
    "\uffe0\035\uffe0\036\uffe0\040\uffe0\050\uffe0\001\002\000\030" +
    "\011\070\014\072\022\057\023\064\024\067\025\071\026" +
    "\074\027\063\031\061\032\142\050\054\001\002\000\036" +
    "\032\uffc1\033\153\034\uffc1\037\uffc1\040\uffc1\046\uffc1\051" +
    "\uffc1\053\uffc1\054\uffc1\055\uffc1\056\uffc1\057\uffc1\060\uffc1" +
    "\061\uffc1\001\002\000\004\032\147\001\002\000\032\032" +
    "\uffbf\037\145\040\uffbf\046\103\051\113\053\110\054\106" +
    "\055\107\056\102\057\112\060\111\061\104\001\002\000" +
    "\026\011\070\014\072\022\057\023\064\024\067\025\071" +
    "\026\074\027\063\031\061\050\054\001\002\000\006\032" +
    "\uffc0\040\uffc0\001\002\000\036\032\uffc2\033\150\034\uffc2" +
    "\037\uffc2\040\uffc2\046\uffc2\051\uffc2\053\uffc2\054\uffc2\055" +
    "\uffc2\056\uffc2\057\uffc2\060\uffc2\061\uffc2\001\002\000\026" +
    "\011\070\014\072\022\057\023\064\024\067\025\071\026" +
    "\074\027\063\031\061\050\054\001\002\000\026\034\152" +
    "\046\103\051\113\053\110\054\106\055\107\056\102\057" +
    "\112\060\111\061\104\001\002\000\044\032\uffbb\033\uffbb" +
    "\034\uffbb\037\uffbb\040\uffbb\042\uffbb\045\uffbb\046\uffbb\051" +
    "\uffbb\052\uffbb\053\uffbb\054\uffbb\055\uffbb\056\uffbb\057\uffbb" +
    "\060\uffbb\061\uffbb\001\002\000\026\011\070\014\072\022" +
    "\057\023\064\024\067\025\071\026\074\027\063\031\061" +
    "\050\054\001\002\000\026\034\155\046\103\051\113\053" +
    "\110\054\106\055\107\056\102\057\112\060\111\061\104" +
    "\001\002\000\044\032\uffba\033\uffba\034\uffba\037\uffba\040" +
    "\uffba\042\uffba\045\uffba\046\uffba\051\uffba\052\uffba\053\uffba" +
    "\054\uffba\055\uffba\056\uffba\057\uffba\060\uffba\061\uffba\001" +
    "\002\000\026\032\157\046\103\051\113\053\110\054\106" +
    "\055\107\056\102\057\112\060\111\061\104\001\002\000" +
    "\034\032\uffcc\034\uffcc\037\uffcc\040\uffcc\046\uffcc\051\uffcc" +
    "\053\uffcc\054\uffcc\055\uffcc\056\uffcc\057\uffcc\060\uffcc\061" +
    "\uffcc\001\002\000\026\011\070\014\072\022\057\023\064" +
    "\024\067\025\071\026\074\027\063\031\061\050\054\001" +
    "\002\000\026\032\162\046\103\051\113\053\110\054\106" +
    "\055\107\056\102\057\112\060\111\061\104\001\002\000" +
    "\044\005\056\006\060\010\055\011\070\012\065\013\050" +
    "\014\072\022\057\023\064\024\067\025\071\026\074\027" +
    "\063\031\061\035\046\040\053\050\054\001\002\000\050" +
    "\005\uffe4\006\uffe4\007\164\010\uffe4\011\uffe4\012\uffe4\013" +
    "\uffe4\014\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\026\uffe4" +
    "\027\uffe4\031\uffe4\035\uffe4\036\uffe4\040\uffe4\050\uffe4\001" +
    "\002\000\044\005\056\006\060\010\055\011\070\012\065" +
    "\013\050\014\072\022\057\023\064\024\067\025\071\026" +
    "\074\027\063\031\061\035\046\040\053\050\054\001\002" +
    "\000\050\005\uffe3\006\uffe3\007\uffe3\010\uffe3\011\uffe3\012" +
    "\uffe3\013\uffe3\014\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3" +
    "\026\uffe3\027\uffe3\031\uffe3\035\uffe3\036\uffe3\040\uffe3\050" +
    "\uffe3\001\002\000\026\011\070\014\072\022\057\023\064" +
    "\024\067\025\071\026\074\027\167\031\061\050\054\001" +
    "\002\000\036\031\141\032\uffbe\033\uffbe\041\174\042\uffbe" +
    "\046\uffbe\051\uffbe\053\uffbe\054\uffbe\055\uffbe\056\uffbe\057" +
    "\uffbe\060\uffbe\061\uffbe\001\002\000\004\032\172\001\002" +
    "\000\026\032\uffd7\046\103\051\113\053\110\054\106\055" +
    "\107\056\102\057\112\060\111\061\104\001\002\000\044" +
    "\005\056\006\060\010\055\011\070\012\065\013\050\014" +
    "\072\022\057\023\064\024\067\025\071\026\074\027\063" +
    "\031\061\035\046\040\053\050\054\001\002\000\050\005" +
    "\uffe2\006\uffe2\007\uffe2\010\uffe2\011\uffe2\012\uffe2\013\uffe2" +
    "\014\uffe2\022\uffe2\023\uffe2\024\uffe2\025\uffe2\026\uffe2\027" +
    "\uffe2\031\uffe2\035\uffe2\036\uffe2\040\uffe2\050\uffe2\001\002" +
    "\000\026\011\070\014\072\022\057\023\064\024\067\025" +
    "\071\026\074\027\063\031\061\050\054\001\002\000\026" +
    "\032\uffd8\046\103\051\113\053\110\054\106\055\107\056" +
    "\102\057\112\060\111\061\104\001\002\000\050\005\uffdd" +
    "\006\uffdd\007\uffdd\010\uffdd\011\uffdd\012\uffdd\013\uffdd\014" +
    "\uffdd\022\uffdd\023\uffdd\024\uffdd\025\uffdd\026\uffdd\027\uffdd" +
    "\031\uffdd\035\uffdd\036\uffdd\040\uffdd\050\uffdd\001\002\000" +
    "\004\040\200\001\002\000\050\005\uffde\006\uffde\007\uffde" +
    "\010\uffde\011\uffde\012\uffde\013\uffde\014\uffde\022\uffde\023" +
    "\uffde\024\uffde\025\uffde\026\uffde\027\uffde\031\uffde\035\uffde" +
    "\036\uffde\040\uffde\050\uffde\001\002\000\034\032\uffcd\034" +
    "\uffcd\037\uffcd\040\uffcd\046\uffcd\051\uffcd\053\uffcd\054\uffcd" +
    "\055\uffcd\056\uffcd\057\uffcd\060\uffcd\061\uffcd\001\002\000" +
    "\050\005\uffdb\006\uffdb\007\uffdb\010\uffdb\011\uffdb\012\uffdb" +
    "\013\uffdb\014\uffdb\022\uffdb\023\uffdb\024\uffdb\025\uffdb\026" +
    "\uffdb\027\uffdb\031\uffdb\035\uffdb\036\uffdb\040\uffdb\050\uffdb" +
    "\001\002\000\054\002\uffe7\004\uffe7\005\uffe7\006\uffe7\007" +
    "\uffe7\010\uffe7\011\uffe7\012\uffe7\013\uffe7\014\uffe7\022\uffe7" +
    "\023\uffe7\024\uffe7\025\uffe7\026\uffe7\027\uffe7\031\uffe7\035" +
    "\uffe7\036\uffe7\040\uffe7\050\uffe7\001\002\000\010\033\075" +
    "\040\220\042\076\001\002\000\014\031\214\033\uffbe\040" +
    "\uffbe\042\uffbe\052\uffbe\001\002\000\004\032\207\001\002" +
    "\000\004\051\210\001\002\000\004\027\205\001\002\000" +
    "\010\033\075\042\076\052\212\001\002\000\004\040\213" +
    "\001\002\000\050\005\uffe1\006\uffe1\007\uffe1\010\uffe1\011" +
    "\uffe1\012\uffe1\013\uffe1\014\uffe1\022\uffe1\023\uffe1\024\uffe1" +
    "\025\uffe1\026\uffe1\027\uffe1\031\uffe1\035\uffe1\036\uffe1\040" +
    "\uffe1\050\uffe1\001\002\000\030\011\070\014\072\022\057" +
    "\023\064\024\067\025\071\026\074\027\063\031\061\032" +
    "\215\050\054\001\002\000\004\033\153\001\002\000\004" +
    "\032\217\001\002\000\004\033\150\001\002\000\050\005" +
    "\uffdf\006\uffdf\007\uffdf\010\uffdf\011\uffdf\012\uffdf\013\uffdf" +
    "\014\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf\026\uffdf\027" +
    "\uffdf\031\uffdf\035\uffdf\036\uffdf\040\uffdf\050\uffdf\001\002" +
    "\000\016\015\032\016\026\017\033\020\030\021\024\030" +
    "\031\001\002\000\016\015\032\016\026\017\033\020\030" +
    "\021\024\030\031\001\002\000\006\035\ufff0\047\222\001" +
    "\002\000\004\035\ufff1\001\002\000\004\035\ufff3\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\223\000\014\002\010\003\007\004\004\005\006\006" +
    "\011\001\001\000\004\011\037\001\001\000\012\003\036" +
    "\004\004\005\006\006\011\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\016\010\017\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\007\020\010\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\014\024\015\026\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\012\044\013\043\014\042\015\026\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\016\046" +
    "\001\001\000\014\016\061\017\050\020\065\021\051\024" +
    "\072\001\001\000\002\001\001\000\004\024\203\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\021\200\024\100\001\001\000\010\021\143\023\176" +
    "\024\100\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\021\155\024\100\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\016\061\017\133\020\065\021\051\024\072" +
    "\001\001\000\002\001\001\000\006\014\127\015\026\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\021\125\024\100\001\001\000" +
    "\002\001\001\000\006\021\077\024\100\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\021\123\024\100\001" +
    "\001\000\006\021\122\024\100\001\001\000\006\021\121" +
    "\024\100\001\001\000\002\001\001\000\006\021\120\024" +
    "\100\001\001\000\006\021\117\024\100\001\001\000\006" +
    "\021\116\024\100\001\001\000\006\021\115\024\100\001" +
    "\001\000\006\021\114\024\100\001\001\000\006\021\113" +
    "\024\100\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\021\131\024\100\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\021\135\024\100\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\021\143\023\142\024\100" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\021\143\023\145\024\100\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\021\150\024\100\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\021\153" +
    "\024\100\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\021\160\024\100" +
    "\001\001\000\002\001\001\000\012\016\061\020\162\021" +
    "\051\024\072\001\001\000\002\001\001\000\012\016\061" +
    "\020\164\021\051\024\072\001\001\000\002\001\001\000" +
    "\010\021\170\022\167\024\100\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\016\061\020" +
    "\172\021\051\024\072\001\001\000\002\001\001\000\006" +
    "\021\174\024\100\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\024\210\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\021\143\023\215\024\100\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\012\224\013\043\014\042\015\026" +
    "\001\001\000\010\013\223\014\222\015\026\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Lang2Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Lang2Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Lang2Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.nextToken(); 
    }


    private CalcLexer s;
    
    public Lang2Parser(CalcLexer s){ 
        this.s=s; 
    }
    
    public void syntax_error(Symbol s){ 
        System.out.println("Erro de sintaxe (linha " + s.left + ", coluna " + s.right + "): Token inesperado '" + (s.value == null ? s.sym : s.value) + "'"); 
    }
    
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        throw new Exception("Erro sintático irrecuperável");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Lang2Parser$actions {
  private final Lang2Parser parser;

  /** Constructor */
  CUP$Lang2Parser$actions(Lang2Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Lang2Parser$do_action_part00000000(
    int                        CUP$Lang2Parser$act_num,
    java_cup.runtime.lr_parser CUP$Lang2Parser$parser,
    java.util.Stack            CUP$Lang2Parser$stack,
    int                        CUP$Lang2Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Lang2Parser$result;

      /* select the action based on the action number */
      switch (CUP$Lang2Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		RESULT = start_val;
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Lang2Parser$parser.done_parsing();
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= decl_list 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // prog ::= 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // decl_list ::= decl decl_list 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("decl_list",1, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // decl_list ::= decl 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("decl_list",1, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // decl ::= data_decl 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("decl",2, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // decl ::= func_decl 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("decl",2, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // data_decl ::= DATA TYID LBRACE bind_list RBRACE 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("data_decl",3, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // bind_list ::= bind bind_list 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("bind_list",5, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // bind_list ::= 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("bind_list",5, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // bind ::= ID COLON type SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("bind",6, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // func_decl ::= ID param_list DCOLON type_annot block 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("func_decl",4, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // param_list ::= param_list ID 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // param_list ::= 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // type_annot ::= type ARROW type_annot 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("type_annot",8, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // type_annot ::= ty_join 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("type_annot",8, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ty_join ::= type TYPE_AND ty_join 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("ty_join",9, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ty_join ::= type 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("ty_join",9, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // type ::= basic_type LBRACKET RBRACKET 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("type",10, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // type ::= basic_type 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("type",10, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // basic_type ::= TYINT 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // basic_type ::= TYCHAR 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // basic_type ::= TYBOOL 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // basic_type ::= TYFLOAT 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // basic_type ::= VOID 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // basic_type ::= TYID 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // block ::= LBRACE cmd_list RBRACE 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("block",12, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // cmd_list ::= cmd cmd_list 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd_list",13, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // cmd_list ::= 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd_list",13, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // cmd ::= IF LPAREN expr RPAREN cmd 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // cmd ::= IF LPAREN expr RPAREN cmd ELSE cmd 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // cmd ::= ITERATE LPAREN loop_cond RPAREN cmd 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // cmd ::= READ LPAREN RPAREN LT lvalue GT SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // cmd ::= PRINT LPAREN expr RPAREN SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // cmd ::= READ lvalue SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // cmd ::= RETURN expr_list_ne SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // cmd ::= RETURN SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // cmd ::= lvalue ASSIGN expr SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // cmd ::= expr SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // cmd ::= block 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // cmd ::= SEMI 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // loop_cond ::= ID COLON expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("loop_cond",16, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // loop_cond ::= expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("loop_cond",16, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr PLUS expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr MINUS expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr TIMES expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr DIV expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr MOD expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr AND expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr EQ expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr NEQ expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= expr LT expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= NOT expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= LPAREN expr RPAREN 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= NEW type 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= NEW type LBRACKET expr RBRACKET 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= NULL 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= INT_LIT 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= FLOAT_LIT 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= CHAR_LIT 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= TRUE 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= FALSE 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= lvalue 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= ID LPAREN expr_list_ne RPAREN 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= ID LPAREN RPAREN 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr_list_ne ::= expr COMMA expr_list_ne 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr_list_ne",17, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr_list_ne ::= expr 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr_list_ne",17, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // lvalue ::= ID 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // lvalue ::= lvalue LBRACKET expr RBRACKET 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // lvalue ::= lvalue DOT ID 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // lvalue ::= ID LPAREN expr_list_ne RPAREN LBRACKET expr RBRACKET 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // lvalue ::= ID LPAREN RPAREN LBRACKET expr RBRACKET 
            {
              Object RESULT =null;

              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Lang2Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Lang2Parser$do_action(
    int                        CUP$Lang2Parser$act_num,
    java_cup.runtime.lr_parser CUP$Lang2Parser$parser,
    java.util.Stack            CUP$Lang2Parser$stack,
    int                        CUP$Lang2Parser$top)
    throws java.lang.Exception
    {
              return CUP$Lang2Parser$do_action_part00000000(
                               CUP$Lang2Parser$act_num,
                               CUP$Lang2Parser$parser,
                               CUP$Lang2Parser$stack,
                               CUP$Lang2Parser$top);
    }
}

}
