
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package calc.parser;

import java_cup.runtime.*;
import calc.nodes.*;
import calc.nodes.decl.*;
import calc.nodes.expr.*;
import calc.nodes.command.*;
import calc.nodes.types.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Lang2Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Lang2ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public Lang2Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Lang2Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Lang2Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\112\000\002\002\004\000\002\002\003\000\002\002" +
    "\002\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\005\007\000\002\007\004\000" +
    "\002\007\002\000\002\010\006\000\002\010\006\000\002" +
    "\006\007\000\002\011\004\000\002\011\002\000\002\012" +
    "\005\000\002\012\003\000\002\013\005\000\002\013\003" +
    "\000\002\014\005\000\002\014\003\000\002\015\003\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\015\003\000\002\015\003\000\002\016\005\000\002\017" +
    "\004\000\002\017\002\000\002\020\007\000\002\020\011" +
    "\000\002\020\011\000\002\020\007\000\002\020\011\000" +
    "\002\020\007\000\002\020\005\000\002\020\005\000\002" +
    "\020\004\000\002\020\006\000\002\020\004\000\002\020" +
    "\003\000\002\020\003\000\002\020\003\000\002\021\005" +
    "\000\002\021\005\000\002\021\005\000\002\021\005\000" +
    "\002\021\005\000\002\021\005\000\002\021\005\000\002" +
    "\021\005\000\002\021\005\000\002\021\005\000\002\021" +
    "\004\000\002\021\005\000\002\021\004\000\002\021\007" +
    "\000\002\021\003\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\021\003\000\002\021\003\000\002" +
    "\021\003\000\002\021\006\000\002\021\005\000\002\023" +
    "\005\000\002\023\003\000\002\024\003\000\002\024\006" +
    "\000\002\024\005\000\002\024\011\000\002\024\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\234\000\010\002\uffff\004\006\027\004\001\002\000" +
    "\006\027\ufff3\043\ufff3\001\002\000\010\002\ufffd\004\006" +
    "\027\004\001\002\000\004\030\014\001\002\000\010\002" +
    "\ufffc\004\ufffc\027\ufffc\001\002\000\004\002\000\001\002" +
    "\000\004\002\013\001\002\000\010\002\ufffb\004\ufffb\027" +
    "\ufffb\001\002\000\004\002\001\001\002\000\004\035\015" +
    "\001\002\000\006\027\016\036\ufff8\001\002\000\006\041" +
    "\024\043\023\001\002\000\004\036\022\001\002\000\006" +
    "\027\016\036\ufff8\001\002\000\004\036\ufff9\001\002\000" +
    "\010\002\ufffa\004\ufffa\027\ufffa\001\002\000\016\015\033" +
    "\016\026\017\034\020\030\021\025\030\031\001\002\000" +
    "\016\015\033\016\026\017\034\020\030\021\025\030\031" +
    "\001\002\000\014\033\uffe9\035\uffe9\040\uffe9\044\uffe9\047" +
    "\uffe9\001\002\000\014\033\uffec\035\uffec\040\uffec\044\uffec" +
    "\047\uffec\001\002\000\004\040\037\001\002\000\014\033" +
    "\uffea\035\uffea\040\uffea\044\uffea\047\uffea\001\002\000\014" +
    "\033\uffe7\035\uffe7\040\uffe7\044\uffe7\047\uffe7\001\002\000" +
    "\014\033\035\035\uffed\040\uffed\044\uffed\047\uffed\001\002" +
    "\000\014\033\uffe8\035\uffe8\040\uffe8\044\uffe8\047\uffe8\001" +
    "\002\000\014\033\uffeb\035\uffeb\040\uffeb\044\uffeb\047\uffeb" +
    "\001\002\000\004\034\036\001\002\000\012\035\uffee\040" +
    "\uffee\044\uffee\047\uffee\001\002\000\050\005\ufff7\006\ufff7" +
    "\007\ufff7\010\ufff7\011\ufff7\012\ufff7\013\ufff7\014\ufff7\022" +
    "\ufff7\023\ufff7\024\ufff7\025\ufff7\026\ufff7\027\ufff7\031\ufff7" +
    "\035\ufff7\036\ufff7\040\ufff7\050\ufff7\001\002\000\004\040" +
    "\041\001\002\000\050\005\ufff6\006\ufff6\007\ufff6\010\ufff6" +
    "\011\ufff6\012\ufff6\013\ufff6\014\ufff6\022\ufff6\023\ufff6\024" +
    "\ufff6\025\ufff6\026\ufff6\027\ufff6\031\ufff6\035\ufff6\036\ufff6" +
    "\040\ufff6\050\ufff6\001\002\000\004\002\ufffe\001\002\000" +
    "\006\027\044\043\045\001\002\000\006\027\ufff4\043\ufff4" +
    "\001\002\000\016\015\033\016\026\017\034\020\030\021" +
    "\025\030\031\001\002\000\010\035\uffef\044\232\047\233" +
    "\001\002\000\004\035\ufff1\001\002\000\004\035\051\001" +
    "\002\000\046\005\061\006\063\010\060\011\073\012\070" +
    "\013\053\014\075\022\062\023\067\024\072\025\074\026" +
    "\077\027\066\031\064\035\051\036\uffe4\040\056\050\057" +
    "\001\002\000\010\002\ufff5\004\ufff5\027\ufff5\001\002\000" +
    "\006\027\215\031\217\001\002\000\004\036\214\001\002" +
    "\000\030\040\213\046\110\051\122\052\120\053\116\054" +
    "\114\055\115\056\111\057\121\060\117\061\112\001\002" +
    "\000\050\005\uffd7\006\uffd7\007\uffd7\010\uffd7\011\uffd7\012" +
    "\uffd7\013\uffd7\014\uffd7\022\uffd7\023\uffd7\024\uffd7\025\uffd7" +
    "\026\uffd7\027\uffd7\031\uffd7\035\uffd7\036\uffd7\040\uffd7\050" +
    "\uffd7\001\002\000\026\011\073\014\075\022\062\023\067" +
    "\024\072\025\074\026\077\027\105\031\064\050\057\001" +
    "\002\000\030\011\073\014\075\022\062\023\067\024\072" +
    "\025\074\026\077\027\105\031\064\040\207\050\057\001" +
    "\002\000\004\031\176\001\002\000\036\032\uffc3\034\uffc3" +
    "\037\uffc3\040\uffc3\046\uffc3\051\uffc3\052\uffc3\053\uffc3\054" +
    "\uffc3\055\uffc3\056\uffc3\057\uffc3\060\uffc3\061\uffc3\001\002" +
    "\000\004\031\170\001\002\000\026\011\073\014\075\022" +
    "\062\023\067\024\072\025\074\026\077\027\105\031\064" +
    "\050\057\001\002\000\050\005\uffd8\006\uffd8\007\uffd8\010" +
    "\uffd8\011\uffd8\012\uffd8\013\uffd8\014\uffd8\022\uffd8\023\uffd8" +
    "\024\uffd8\025\uffd8\026\uffd8\027\uffd8\031\uffd8\035\uffd8\036" +
    "\uffd8\040\uffd8\050\uffd8\001\002\000\044\031\135\033\uffbc" +
    "\040\uffbc\041\024\042\uffbc\043\023\045\uffbc\046\uffbc\051" +
    "\uffbc\052\uffbc\053\uffbc\054\uffbc\055\uffbc\056\uffbc\057\uffbc" +
    "\060\uffbc\061\uffbc\001\002\000\036\032\uffc2\034\uffc2\037" +
    "\uffc2\040\uffc2\046\uffc2\051\uffc2\052\uffc2\053\uffc2\054\uffc2" +
    "\055\uffc2\056\uffc2\057\uffc2\060\uffc2\061\uffc2\001\002\000" +
    "\004\031\162\001\002\000\046\005\061\006\063\010\060" +
    "\011\073\012\070\013\053\014\075\022\062\023\067\024" +
    "\072\025\074\026\077\027\066\031\064\035\051\036\uffe4" +
    "\040\056\050\057\001\002\000\036\032\uffc6\034\uffc6\037" +
    "\uffc6\040\uffc6\046\uffc6\051\uffc6\052\uffc6\053\uffc6\054\uffc6" +
    "\055\uffc6\056\uffc6\057\uffc6\060\uffc6\061\uffc6\001\002\000" +
    "\016\015\033\016\026\017\034\020\030\021\025\030\154" +
    "\001\002\000\036\032\uffc5\034\uffc5\037\uffc5\040\uffc5\046" +
    "\uffc5\051\uffc5\052\uffc5\053\uffc5\054\uffc5\055\uffc5\056\uffc5" +
    "\057\uffc5\060\uffc5\061\uffc5\001\002\000\036\032\uffc7\034" +
    "\uffc7\037\uffc7\040\uffc7\046\uffc7\051\uffc7\052\uffc7\053\uffc7" +
    "\054\uffc7\055\uffc7\056\uffc7\057\uffc7\060\uffc7\061\uffc7\001" +
    "\002\000\036\033\101\040\uffc1\042\103\045\102\046\uffc1" +
    "\051\uffc1\052\uffc1\053\uffc1\054\uffc1\055\uffc1\056\uffc1\057" +
    "\uffc1\060\uffc1\061\uffc1\001\002\000\036\032\uffc4\034\uffc4" +
    "\037\uffc4\040\uffc4\046\uffc4\051\uffc4\052\uffc4\053\uffc4\054" +
    "\uffc4\055\uffc4\056\uffc4\057\uffc4\060\uffc4\061\uffc4\001\002" +
    "\000\050\005\uffd6\006\uffd6\007\uffd6\010\uffd6\011\uffd6\012" +
    "\uffd6\013\uffd6\014\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6" +
    "\026\uffd6\027\uffd6\031\uffd6\035\uffd6\036\uffd6\040\uffd6\050" +
    "\uffd6\001\002\000\026\011\073\014\075\022\062\023\067" +
    "\024\072\025\074\026\077\027\105\031\064\050\057\001" +
    "\002\000\026\011\073\014\075\022\062\023\067\024\072" +
    "\025\074\026\077\027\105\031\064\050\057\001\002\000" +
    "\004\027\104\001\002\000\044\032\uffba\033\uffba\034\uffba" +
    "\037\uffba\040\uffba\042\uffba\045\uffba\046\uffba\051\uffba\052" +
    "\uffba\053\uffba\054\uffba\055\uffba\056\uffba\057\uffba\060\uffba" +
    "\061\uffba\001\002\000\044\031\135\032\uffbc\033\uffbc\034" +
    "\uffbc\037\uffbc\040\uffbc\042\uffbc\046\uffbc\051\uffbc\052\uffbc" +
    "\053\uffbc\054\uffbc\055\uffbc\056\uffbc\057\uffbc\060\uffbc\061" +
    "\uffbc\001\002\000\030\040\113\046\110\051\122\052\120" +
    "\053\116\054\114\055\115\056\111\057\121\060\117\061" +
    "\112\001\002\000\042\032\uffc1\033\101\034\uffc1\037\uffc1" +
    "\040\uffc1\042\103\046\uffc1\051\uffc1\052\uffc1\053\uffc1\054" +
    "\uffc1\055\uffc1\056\uffc1\057\uffc1\060\uffc1\061\uffc1\001\002" +
    "\000\026\011\073\014\075\022\062\023\067\024\072\025" +
    "\074\026\077\027\105\031\064\050\057\001\002\000\026" +
    "\011\073\014\075\022\062\023\067\024\072\025\074\026" +
    "\077\027\105\031\064\050\057\001\002\000\026\011\073" +
    "\014\075\022\062\023\067\024\072\025\074\026\077\027" +
    "\105\031\064\050\057\001\002\000\050\005\uffda\006\uffda" +
    "\007\uffda\010\uffda\011\uffda\012\uffda\013\uffda\014\uffda\022" +
    "\uffda\023\uffda\024\uffda\025\uffda\026\uffda\027\uffda\031\uffda" +
    "\035\uffda\036\uffda\040\uffda\050\uffda\001\002\000\026\011" +
    "\073\014\075\022\062\023\067\024\072\025\074\026\077" +
    "\027\105\031\064\050\057\001\002\000\026\011\073\014" +
    "\075\022\062\023\067\024\072\025\074\026\077\027\105" +
    "\031\064\050\057\001\002\000\026\011\073\014\075\022" +
    "\062\023\067\024\072\025\074\026\077\027\105\031\064" +
    "\050\057\001\002\000\026\011\073\014\075\022\062\023" +
    "\067\024\072\025\074\026\077\027\105\031\064\050\057" +
    "\001\002\000\026\011\073\014\075\022\062\023\067\024" +
    "\072\025\074\026\077\027\105\031\064\050\057\001\002" +
    "\000\026\011\073\014\075\022\062\023\067\024\072\025" +
    "\074\026\077\027\105\031\064\050\057\001\002\000\026" +
    "\011\073\014\075\022\062\023\067\024\072\025\074\026" +
    "\077\027\105\031\064\050\057\001\002\000\026\032\uffcd" +
    "\034\uffcd\037\uffcd\040\uffcd\046\uffcd\055\115\056\111\057" +
    "\121\060\117\061\112\001\002\000\036\032\uffd3\034\uffd3" +
    "\037\uffd3\040\uffd3\046\uffd3\051\uffd3\052\uffd3\053\uffd3\054" +
    "\uffd3\055\uffd3\056\uffd3\057\uffd3\060\uffd3\061\uffd3\001\002" +
    "\000\026\032\uffcc\034\uffcc\037\uffcc\040\uffcc\046\uffcc\055" +
    "\115\056\111\057\121\060\117\061\112\001\002\000\036" +
    "\032\uffd2\034\uffd2\037\uffd2\040\uffd2\046\uffd2\051\uffd2\052" +
    "\uffd2\053\uffd2\054\uffd2\055\uffd2\056\uffd2\057\uffd2\060\uffd2" +
    "\061\uffd2\001\002\000\026\032\uffcf\034\uffcf\037\uffcf\040" +
    "\uffcf\046\uffcf\055\115\056\111\057\121\060\117\061\112" +
    "\001\002\000\036\032\uffd5\034\uffd5\037\uffd5\040\uffd5\046" +
    "\uffd5\051\uffd5\052\uffd5\053\uffd5\054\uffd5\055\uffd5\056\uffd5" +
    "\057\121\060\117\061\112\001\002\000\026\032\uffce\034" +
    "\uffce\037\uffce\040\uffce\046\uffce\055\115\056\111\057\121" +
    "\060\117\061\112\001\002\000\036\032\uffd1\034\uffd1\037" +
    "\uffd1\040\uffd1\046\uffd1\051\uffd1\052\uffd1\053\uffd1\054\uffd1" +
    "\055\uffd1\056\uffd1\057\uffd1\060\uffd1\061\uffd1\001\002\000" +
    "\036\032\uffd4\034\uffd4\037\uffd4\040\uffd4\046\uffd4\051\uffd4" +
    "\052\uffd4\053\uffd4\054\uffd4\055\uffd4\056\uffd4\057\121\060" +
    "\117\061\112\001\002\000\036\032\uffd0\034\uffd0\037\uffd0" +
    "\040\uffd0\046\uffd0\051\122\052\120\053\116\054\114\055" +
    "\115\056\111\057\121\060\117\061\112\001\002\000\030" +
    "\011\073\014\075\022\062\023\067\024\072\025\074\026" +
    "\077\027\105\031\064\032\136\050\057\001\002\000\040" +
    "\032\uffbf\033\147\034\uffbf\037\uffbf\040\uffbf\046\uffbf\051" +
    "\uffbf\052\uffbf\053\uffbf\054\uffbf\055\uffbf\056\uffbf\057\uffbf" +
    "\060\uffbf\061\uffbf\001\002\000\004\032\143\001\002\000" +
    "\034\032\uffbd\037\141\040\uffbd\046\110\051\122\052\120" +
    "\053\116\054\114\055\115\056\111\057\121\060\117\061" +
    "\112\001\002\000\026\011\073\014\075\022\062\023\067" +
    "\024\072\025\074\026\077\027\105\031\064\050\057\001" +
    "\002\000\006\032\uffbe\040\uffbe\001\002\000\040\032\uffc0" +
    "\033\144\034\uffc0\037\uffc0\040\uffc0\046\uffc0\051\uffc0\052" +
    "\uffc0\053\uffc0\054\uffc0\055\uffc0\056\uffc0\057\uffc0\060\uffc0" +
    "\061\uffc0\001\002\000\026\011\073\014\075\022\062\023" +
    "\067\024\072\025\074\026\077\027\105\031\064\050\057" +
    "\001\002\000\030\034\146\046\110\051\122\052\120\053" +
    "\116\054\114\055\115\056\111\057\121\060\117\061\112" +
    "\001\002\000\044\032\uffb9\033\uffb9\034\uffb9\037\uffb9\040" +
    "\uffb9\042\uffb9\045\uffb9\046\uffb9\051\uffb9\052\uffb9\053\uffb9" +
    "\054\uffb9\055\uffb9\056\uffb9\057\uffb9\060\uffb9\061\uffb9\001" +
    "\002\000\026\011\073\014\075\022\062\023\067\024\072" +
    "\025\074\026\077\027\105\031\064\050\057\001\002\000" +
    "\030\034\151\046\110\051\122\052\120\053\116\054\114" +
    "\055\115\056\111\057\121\060\117\061\112\001\002\000" +
    "\044\032\uffb8\033\uffb8\034\uffb8\037\uffb8\040\uffb8\042\uffb8" +
    "\045\uffb8\046\uffb8\051\uffb8\052\uffb8\053\uffb8\054\uffb8\055" +
    "\uffb8\056\uffb8\057\uffb8\060\uffb8\061\uffb8\001\002\000\030" +
    "\034\153\046\110\051\122\052\120\053\116\054\114\055" +
    "\115\056\111\057\121\060\117\061\112\001\002\000\044" +
    "\032\uffbb\033\uffbb\034\uffbb\037\uffbb\040\uffbb\042\uffbb\045" +
    "\uffbb\046\uffbb\051\uffbb\052\uffbb\053\uffbb\054\uffbb\055\uffbb" +
    "\056\uffbb\057\uffbb\060\uffbb\061\uffbb\001\002\000\040\032" +
    "\uffc9\033\uffe7\034\uffc9\037\uffc9\040\uffc9\046\uffc9\051\uffc9" +
    "\052\uffc9\053\uffc9\054\uffc9\055\uffc9\056\uffc9\057\uffc9\060" +
    "\uffc9\061\uffc9\001\002\000\004\033\156\001\002\000\026" +
    "\011\073\014\075\022\062\023\067\024\072\025\074\026" +
    "\077\027\105\031\064\050\057\001\002\000\030\034\160" +
    "\046\110\051\122\052\120\053\116\054\114\055\115\056" +
    "\111\057\121\060\117\061\112\001\002\000\036\032\uffc8" +
    "\034\uffc8\037\uffc8\040\uffc8\046\uffc8\051\uffc8\052\uffc8\053" +
    "\uffc8\054\uffc8\055\uffc8\056\uffc8\057\uffc8\060\uffc8\061\uffc8" +
    "\001\002\000\004\036\uffe5\001\002\000\026\011\073\014" +
    "\075\022\062\023\067\024\072\025\074\026\077\027\105" +
    "\031\064\050\057\001\002\000\030\032\164\046\110\051" +
    "\122\052\120\053\116\054\114\055\115\056\111\057\121" +
    "\060\117\061\112\001\002\000\004\040\165\001\002\000" +
    "\050\005\uffde\006\uffde\007\uffde\010\uffde\011\uffde\012\uffde" +
    "\013\uffde\014\uffde\022\uffde\023\uffde\024\uffde\025\uffde\026" +
    "\uffde\027\uffde\031\uffde\035\uffde\036\uffde\040\uffde\050\uffde" +
    "\001\002\000\030\032\167\046\110\051\122\052\120\053" +
    "\116\054\114\055\115\056\111\057\121\060\117\061\112" +
    "\001\002\000\036\032\uffca\034\uffca\037\uffca\040\uffca\046" +
    "\uffca\051\uffca\052\uffca\053\uffca\054\uffca\055\uffca\056\uffca" +
    "\057\uffca\060\uffca\061\uffca\001\002\000\026\011\073\014" +
    "\075\022\062\023\067\024\072\025\074\026\077\027\105" +
    "\031\064\050\057\001\002\000\030\032\172\046\110\051" +
    "\122\052\120\053\116\054\114\055\115\056\111\057\121" +
    "\060\117\061\112\001\002\000\044\005\061\006\063\010" +
    "\060\011\073\012\070\013\053\014\075\022\062\023\067" +
    "\024\072\025\074\026\077\027\066\031\064\035\051\040" +
    "\056\050\057\001\002\000\050\005\uffe3\006\uffe3\007\174" +
    "\010\uffe3\011\uffe3\012\uffe3\013\uffe3\014\uffe3\022\uffe3\023" +
    "\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\031\uffe3\035\uffe3" +
    "\036\uffe3\040\uffe3\050\uffe3\001\002\000\044\005\061\006" +
    "\063\010\060\011\073\012\070\013\053\014\075\022\062" +
    "\023\067\024\072\025\074\026\077\027\066\031\064\035" +
    "\051\040\056\050\057\001\002\000\050\005\uffe2\006\uffe2" +
    "\007\uffe2\010\uffe2\011\uffe2\012\uffe2\013\uffe2\014\uffe2\022" +
    "\uffe2\023\uffe2\024\uffe2\025\uffe2\026\uffe2\027\uffe2\031\uffe2" +
    "\035\uffe2\036\uffe2\040\uffe2\050\uffe2\001\002\000\026\011" +
    "\073\014\075\022\062\023\067\024\072\025\074\026\077" +
    "\027\177\031\064\050\057\001\002\000\040\031\135\032" +
    "\uffbc\033\uffbc\041\203\042\uffbc\046\uffbc\051\uffbc\052\uffbc" +
    "\053\uffbc\054\uffbc\055\uffbc\056\uffbc\057\uffbc\060\uffbc\061" +
    "\uffbc\001\002\000\030\032\201\046\110\051\122\052\120" +
    "\053\116\054\114\055\115\056\111\057\121\060\117\061" +
    "\112\001\002\000\044\005\061\006\063\010\060\011\073" +
    "\012\070\013\053\014\075\022\062\023\067\024\072\025" +
    "\074\026\077\027\066\031\064\035\051\040\056\050\057" +
    "\001\002\000\050\005\uffe0\006\uffe0\007\uffe0\010\uffe0\011" +
    "\uffe0\012\uffe0\013\uffe0\014\uffe0\022\uffe0\023\uffe0\024\uffe0" +
    "\025\uffe0\026\uffe0\027\uffe0\031\uffe0\035\uffe0\036\uffe0\040" +
    "\uffe0\050\uffe0\001\002\000\026\011\073\014\075\022\062" +
    "\023\067\024\072\025\074\026\077\027\105\031\064\050" +
    "\057\001\002\000\030\032\205\046\110\051\122\052\120" +
    "\053\116\054\114\055\115\056\111\057\121\060\117\061" +
    "\112\001\002\000\044\005\061\006\063\010\060\011\073" +
    "\012\070\013\053\014\075\022\062\023\067\024\072\025" +
    "\074\026\077\027\066\031\064\035\051\040\056\050\057" +
    "\001\002\000\050\005\uffe1\006\uffe1\007\uffe1\010\uffe1\011" +
    "\uffe1\012\uffe1\013\uffe1\014\uffe1\022\uffe1\023\uffe1\024\uffe1" +
    "\025\uffe1\026\uffe1\027\uffe1\031\uffe1\035\uffe1\036\uffe1\040" +
    "\uffe1\050\uffe1\001\002\000\050\005\uffdb\006\uffdb\007\uffdb" +
    "\010\uffdb\011\uffdb\012\uffdb\013\uffdb\014\uffdb\022\uffdb\023" +
    "\uffdb\024\uffdb\025\uffdb\026\uffdb\027\uffdb\031\uffdb\035\uffdb" +
    "\036\uffdb\040\uffdb\050\uffdb\001\002\000\004\040\211\001" +
    "\002\000\050\005\uffdc\006\uffdc\007\uffdc\010\uffdc\011\uffdc" +
    "\012\uffdc\013\uffdc\014\uffdc\022\uffdc\023\uffdc\024\uffdc\025" +
    "\uffdc\026\uffdc\027\uffdc\031\uffdc\035\uffdc\036\uffdc\040\uffdc" +
    "\050\uffdc\001\002\000\036\032\uffcb\034\uffcb\037\uffcb\040" +
    "\uffcb\046\uffcb\051\uffcb\052\uffcb\053\uffcb\054\uffcb\055\uffcb" +
    "\056\uffcb\057\uffcb\060\uffcb\061\uffcb\001\002\000\050\005" +
    "\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012\uffd9\013\uffd9" +
    "\014\uffd9\022\uffd9\023\uffd9\024\uffd9\025\uffd9\026\uffd9\027" +
    "\uffd9\031\uffd9\035\uffd9\036\uffd9\040\uffd9\050\uffd9\001\002" +
    "\000\054\002\uffe6\004\uffe6\005\uffe6\006\uffe6\007\uffe6\010" +
    "\uffe6\011\uffe6\012\uffe6\013\uffe6\014\uffe6\022\uffe6\023\uffe6" +
    "\024\uffe6\025\uffe6\026\uffe6\027\uffe6\031\uffe6\035\uffe6\036" +
    "\uffe6\040\uffe6\050\uffe6\001\002\000\014\031\226\033\uffbc" +
    "\040\uffbc\042\uffbc\052\uffbc\001\002\000\010\033\101\040" +
    "\225\042\103\001\002\000\004\032\220\001\002\000\004" +
    "\051\221\001\002\000\004\027\215\001\002\000\010\033" +
    "\101\042\103\052\223\001\002\000\004\040\224\001\002" +
    "\000\050\005\uffdf\006\uffdf\007\uffdf\010\uffdf\011\uffdf\012" +
    "\uffdf\013\uffdf\014\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf" +
    "\026\uffdf\027\uffdf\031\uffdf\035\uffdf\036\uffdf\040\uffdf\050" +
    "\uffdf\001\002\000\050\005\uffdd\006\uffdd\007\uffdd\010\uffdd" +
    "\011\uffdd\012\uffdd\013\uffdd\014\uffdd\022\uffdd\023\uffdd\024" +
    "\uffdd\025\uffdd\026\uffdd\027\uffdd\031\uffdd\035\uffdd\036\uffdd" +
    "\040\uffdd\050\uffdd\001\002\000\030\011\073\014\075\022" +
    "\062\023\067\024\072\025\074\026\077\027\105\031\064" +
    "\032\227\050\057\001\002\000\004\033\147\001\002\000" +
    "\004\032\231\001\002\000\004\033\144\001\002\000\016" +
    "\015\033\016\026\017\034\020\030\021\025\030\031\001" +
    "\002\000\016\015\033\016\026\017\034\020\030\021\025" +
    "\030\031\001\002\000\006\035\uffef\047\233\001\002\000" +
    "\004\035\ufff0\001\002\000\004\035\ufff2\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\234\000\014\002\010\003\007\004\004\005\006\006" +
    "\011\001\001\000\004\011\042\001\001\000\012\003\041" +
    "\004\004\005\006\006\011\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\016\010\017\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\007\020\010\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\014\037\015\031\001\001\000\006" +
    "\014\026\015\031\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\012\047\013\046\014\045" +
    "\015\031\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\016\051\001\001\000\016\010\077\016\064\017\053" +
    "\020\070\021\054\024\075\001\001\000\002\001\001\000" +
    "\004\024\215\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\021\211\024\106\001\001\000" +
    "\010\021\137\023\207\024\106\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\021\165\024" +
    "\106\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\010\077\016\064\017" +
    "\160\020\070\021\054\024\075\001\001\000\002\001\001" +
    "\000\004\015\154\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\021\151\024\106\001\001\000\006\021\105\024" +
    "\106\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\021" +
    "\133\024\106\001\001\000\006\021\132\024\106\001\001" +
    "\000\006\021\131\024\106\001\001\000\002\001\001\000" +
    "\006\021\130\024\106\001\001\000\006\021\127\024\106" +
    "\001\001\000\006\021\126\024\106\001\001\000\006\021" +
    "\125\024\106\001\001\000\006\021\124\024\106\001\001" +
    "\000\006\021\123\024\106\001\001\000\006\021\122\024" +
    "\106\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\021\137\023\136\024\106\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\021\137\023\141\024\106\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\021\144\024\106\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\021\147\024" +
    "\106\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\021\156\024\106\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\021\162\024" +
    "\106\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\021" +
    "\170\024\106\001\001\000\002\001\001\000\014\010\077" +
    "\016\064\020\172\021\054\024\075\001\001\000\002\001" +
    "\001\000\014\010\077\016\064\020\174\021\054\024\075" +
    "\001\001\000\002\001\001\000\006\021\177\024\106\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\010\077" +
    "\016\064\020\201\021\054\024\075\001\001\000\002\001" +
    "\001\000\006\021\203\024\106\001\001\000\002\001\001" +
    "\000\014\010\077\016\064\020\205\021\054\024\075\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\024\221\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\021\137\023\227\024\106\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\012\235\013\046\014\045\015\031\001\001\000\010\013" +
    "\234\014\233\015\031\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Lang2Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Lang2Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Lang2Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.nextToken(); 
    }


    private CalcLexer s;
    
    public Lang2Parser(CalcLexer s){ 
        this.s=s; 
    }
    
    public void syntax_error(Symbol s){ 
        System.out.println("Erro de sintaxe (linha " + s.left + ", coluna " + s.right + "): Token inesperado '" + (s.value == null ? s.sym : s.value) + "'"); 
    }
    
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        throw new Exception("Erro sintático irrecuperável");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Lang2Parser$actions {
  private final Lang2Parser parser;

  /** Constructor */
  CUP$Lang2Parser$actions(Lang2Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Lang2Parser$do_action_part00000000(
    int                        CUP$Lang2Parser$act_num,
    java_cup.runtime.lr_parser CUP$Lang2Parser$parser,
    java.util.Stack            CUP$Lang2Parser$stack,
    int                        CUP$Lang2Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Lang2Parser$result;

      /* select the action based on the action number */
      switch (CUP$Lang2Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		RESULT = start_val;
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Lang2Parser$parser.done_parsing();
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= decl_list 
            {
              Program RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		ArrayList<CNode> d = (ArrayList<CNode>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Program(0, 0, d); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // prog ::= 
            {
              Program RESULT =null;
		 RESULT = new Program(0, 0, new ArrayList<CNode>()); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // decl_list ::= decl decl_list 
            {
              ArrayList<CNode> RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		CNode d = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		ArrayList<CNode> l = (ArrayList<CNode>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 l.add(0, d); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("decl_list",1, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // decl_list ::= decl 
            {
              ArrayList<CNode> RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CNode d = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 ArrayList<CNode> l = new ArrayList<>(); l.add(d); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("decl_list",1, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // decl ::= data_decl 
            {
              CNode RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		DataDecl d = (DataDecl)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("decl",2, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // decl ::= func_decl 
            {
              CNode RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		FunDef f = (FunDef)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("decl",2, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // data_decl ::= DATA TYID LBRACE bind_list RBRACE 
            {
              DataDecl RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		ArrayList<Bind> b = (ArrayList<Bind>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new DataDecl(nleft, nright, n, b); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("data_decl",3, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // bind_list ::= bind bind_list 
            {
              ArrayList<Bind> RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Bind b = (Bind)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		ArrayList<Bind> l = (ArrayList<Bind>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 l.add(0, b); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("bind_list",5, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // bind_list ::= 
            {
              ArrayList<Bind> RESULT =null;
		 RESULT = new ArrayList<Bind>(); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("bind_list",5, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // bind ::= ID COLON type SEMI 
            {
              Bind RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new Bind(nleft, nright, t, new Var(nleft, nright, n)); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("bind",6, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bind ::= ID DCOLON type SEMI 
            {
              Bind RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new Bind(nleft, nright, t, new Var(nleft, nright, n)); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("bind",6, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // func_decl ::= ID param_list DCOLON type_annot block 
            {
              FunDef RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).right;
		ArrayList<String> p = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).value;
		int typesleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int typesright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		ArrayList<CType> types = (ArrayList<CType>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CNode b = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 
               CType retType = types.get(types.size()-1); 
               ArrayList<Bind> params = new ArrayList<>();
               for(int i=0; i < p.size() && i < types.size()-1; i++) {
                   params.add(new Bind(nleft, nright, types.get(i), new Var(nleft, nright, p.get(i))));
               }
               RESULT = new FunDef(nleft, nright, n, params, retType, b); 
            
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("func_decl",4, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // param_list ::= param_list ID 
            {
              ArrayList<String> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		ArrayList<String> l = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 l.add(n); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // param_list ::= 
            {
              ArrayList<String> RESULT =null;
		 RESULT = new ArrayList<String>(); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // type_annot ::= type ARROW type_annot 
            {
              ArrayList<CType> RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		ArrayList<CType> l = (ArrayList<CType>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 l.add(0, t); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("type_annot",8, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // type_annot ::= ty_join 
            {
              ArrayList<CType> RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 ArrayList<CType> l = new ArrayList<>(); l.add(t); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("type_annot",8, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ty_join ::= type TYPE_AND ty_join 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		 RESULT = t; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("ty_join",9, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ty_join ::= type 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = t; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("ty_join",9, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // type ::= basic_type LBRACKET RBRACKET 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		 RESULT = new TyArr(tleft, tright, t); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("type",10, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // type ::= basic_type 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = t; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("type",10, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // basic_type ::= TYINT 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new TyInt(tleft, tright); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // basic_type ::= TYCHAR 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new TyChar(tleft, tright); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // basic_type ::= TYBOOL 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new TyBool(tleft, tright); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // basic_type ::= TYFLOAT 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new TyFloat(tleft, tright); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // basic_type ::= VOID 
            {
              CType RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new TyVoid(tleft, tright); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // basic_type ::= TYID 
            {
              CType RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new TyId(nleft, nright, n); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("basic_type",11, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // block ::= LBRACE cmd_list RBRACE 
            {
              CNode RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		ArrayList<CNode> l = (ArrayList<CNode>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new CSeq(lleft, lright, l); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("block",12, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // cmd_list ::= cmd cmd_list 
            {
              ArrayList<CNode> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		CNode c = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		ArrayList<CNode> l = (ArrayList<CNode>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 l.add(0, c); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd_list",13, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // cmd_list ::= 
            {
              ArrayList<CNode> RESULT =null;
		 RESULT = new ArrayList<CNode>(); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd_list",13, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // cmd ::= IF LPAREN expr RPAREN cmd 
            {
              CNode RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CNode c = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new If(kleft, kright, e, c, null); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // cmd ::= IF LPAREN expr RPAREN cmd ELSE cmd 
            {
              CNode RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).value;
		int c1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		CNode c1 = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CNode c2 = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new If(kleft, kright, e, c1, c2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // cmd ::= ITERATE LPAREN ID COLON expr RPAREN cmd 
            {
              CNode RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CNode b = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Iterate(kleft, kright, n, e, b); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // cmd ::= ITERATE LPAREN expr RPAREN cmd 
            {
              CNode RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CNode b = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Iterate(kleft, kright, null, e, b); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // cmd ::= READ LPAREN RPAREN LT lvalue GT SEMI 
            {
              CNode RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp l = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		 RESULT = new Read(rleft, rright, l); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // cmd ::= PRINT LPAREN expr RPAREN SEMI 
            {
              CNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		 RESULT = new Print(pleft, pright, e); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // cmd ::= READ lvalue SEMI 
            {
              CNode RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Exp l = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new Read(rleft, rright, l); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // cmd ::= RETURN expr_list_ne SEMI 
            {
              CNode RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int elleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		ArrayList<Exp> el = (ArrayList<Exp>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new Return(rleft, rright, el.get(0)); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // cmd ::= RETURN SEMI 
            {
              CNode RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new Return(rleft, rright, null); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // cmd ::= lvalue ASSIGN expr SEMI 
            {
              CNode RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).right;
		Exp l = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new CAttr(lleft, lright, l, e); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // cmd ::= expr SEMI 
            {
              CNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = e; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // cmd ::= block 
            {
              CNode RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		CNode b = (CNode)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = b; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // cmd ::= SEMI 
            {
              CNode RESULT =null;
		 RESULT = new CSeq(0,0, new ArrayList<CNode>()); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // cmd ::= bind 
            {
              CNode RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Bind b = (Bind)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = b; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("cmd",14, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr PLUS expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Plus(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr MINUS expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Sub(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr TIMES expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Times(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr DIV expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Div(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr MOD expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Mod(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr AND expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new And(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr EQ expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Eq(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= expr NEQ expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Neq(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= expr LT expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Lt(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= expr GT expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Gt(e1left, e1right, e1, e2); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= NOT expr 
            {
              Exp RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Not(nleft, nright, e); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= LPAREN expr RPAREN 
            {
              Exp RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = e; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= NEW TYID 
            {
              Exp RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new New(kleft, kright, new TyId(nleft, nright, n), null); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= NEW basic_type LBRACKET expr RBRACKET 
            {
              Exp RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).right;
		CType t = (CType)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).value;
		int szleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int szright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Exp sz = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new New(kleft, kright, t, sz); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= NULL 
            {
              Exp RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int kright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new IntLit(kleft, kright, 0); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= INT_LIT 
            {
              Exp RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new IntLit(ileft, iright, i); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= FLOAT_LIT 
            {
              Exp RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Float f = (Float)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new FloatLit(fleft, fright, f); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= CHAR_LIT 
            {
              Exp RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new IntLit(cleft, cright, (int)c.charAt(1)); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= TRUE 
            {
              Exp RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Boolean t = (Boolean)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new BoolLit(tleft, tright, true); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= FALSE 
            {
              Exp RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Boolean f = (Boolean)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new BoolLit(fleft, fright, false); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= lvalue 
            {
              Exp RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp l = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= ID LPAREN expr_list_ne RPAREN 
            {
              Exp RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).value;
		int elleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		ArrayList<Exp> el = (ArrayList<Exp>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new FCall(nleft, nright, n, el); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= ID LPAREN RPAREN 
            {
              Exp RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		 RESULT = new FCall(nleft, nright, n, new ArrayList<Exp>()); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr_list_ne ::= expr COMMA expr_list_ne 
            {
              ArrayList<Exp> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		ArrayList<Exp> l = (ArrayList<Exp>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 l.add(0, e); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr_list_ne",17, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expr_list_ne ::= expr 
            {
              ArrayList<Exp> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 ArrayList<Exp> l = new ArrayList<>(); l.add(e); RESULT = l; 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("expr_list_ne",17, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // lvalue ::= ID 
            {
              Exp RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new Var(nleft, nright, n); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // lvalue ::= lvalue LBRACKET expr RBRACKET 
            {
              Exp RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).right;
		Exp l = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new ArrayAccess(lleft, lright, l, e); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // lvalue ::= lvalue DOT ID 
            {
              Exp RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).right;
		Exp l = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.peek()).value;
		 RESULT = new FieldAccess(lleft, lright, l, f); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // lvalue ::= ID LPAREN expr_list_ne RPAREN LBRACKET expr RBRACKET 
            {
              Exp RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)).value;
		int elleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).right;
		ArrayList<Exp> el = (ArrayList<Exp>)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-4)).value;
		int idxleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int idxright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Exp idx = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new FCall(nleft, nright, n, el); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // lvalue ::= ID LPAREN RPAREN LBRACKET expr RBRACKET 
            {
              Exp RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-5)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-5)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-5)).value;
		int idxleft = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).left;
		int idxright = ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).right;
		Exp idx = (Exp)((java_cup.runtime.Symbol) CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-1)).value;
		 RESULT = new FCall(nleft, nright, n, new ArrayList<Exp>()); 
              CUP$Lang2Parser$result = parser.getSymbolFactory().newSymbol("lvalue",18, ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.elementAt(CUP$Lang2Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Lang2Parser$stack.peek()), RESULT);
            }
          return CUP$Lang2Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Lang2Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Lang2Parser$do_action(
    int                        CUP$Lang2Parser$act_num,
    java_cup.runtime.lr_parser CUP$Lang2Parser$parser,
    java.util.Stack            CUP$Lang2Parser$stack,
    int                        CUP$Lang2Parser$top)
    throws java.lang.Exception
    {
              return CUP$Lang2Parser$do_action_part00000000(
                               CUP$Lang2Parser$act_num,
                               CUP$Lang2Parser$parser,
                               CUP$Lang2Parser$stack,
                               CUP$Lang2Parser$top);
    }
}

}
