
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lang.parser;

/** CUP generated class containing symbol constants. */
public class LangParserSym {
  /* terminals */
  public static final int ATTRIB = 19;
  public static final int LBRACKET = 11;
  public static final int CHAR = 34;
  public static final int MENORQ = 13;
  public static final int DIFERENTE = 16;
  public static final int MAIORQ = 14;
  public static final int MINUS = 3;
  public static final int DATA = 25;
  public static final int NOT = 18;
  public static final int AND = 17;
  public static final int IGUAL = 15;
  public static final int LP = 7;
  public static final int COMMA = 21;
  public static final int DIV = 5;
  public static final int RP = 8;
  public static final int PLUS = 2;
  public static final int MAIN = 35;
  public static final int IF = 26;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int RBRACKET = 12;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int NULL = 38;
  public static final int NUMBER = 29;
  public static final int MOD = 6;
  public static final int VOID = 40;
  public static final int TYID = 33;
  public static final int ITERATE = 28;
  public static final int COLONCOLON = 23;
  public static final int TIMES = 4;
  public static final int COLON = 22;
  public static final int LBRACE = 9;
  public static final int ELSE = 27;
  public static final int FLOAT = 39;
  public static final int RBRACE = 10;
  public static final int STRING = 37;
  public static final int FALSE = 31;
  public static final int PRINT = 24;
  public static final int PV = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LP",
  "RP",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "MENORQ",
  "MAIORQ",
  "IGUAL",
  "DIFERENTE",
  "AND",
  "NOT",
  "ATTRIB",
  "PV",
  "COMMA",
  "COLON",
  "COLONCOLON",
  "PRINT",
  "DATA",
  "IF",
  "ELSE",
  "ITERATE",
  "NUMBER",
  "TRUE",
  "FALSE",
  "ID",
  "TYID",
  "CHAR",
  "MAIN",
  "RETURN",
  "STRING",
  "NULL",
  "FLOAT",
  "VOID"
  };
}

