// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lang/parser/lang.flex

package lang.parser;

import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class LangLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\2\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\12\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\0\25\27\1\30\4\27\1\31"+
    "\1\32\1\33\1\0\1\34\1\0\1\35\1\36\1\34"+
    "\1\37\1\40\1\41\2\34\1\42\2\34\1\43\1\44"+
    "\1\45\1\46\1\47\1\34\1\50\1\51\1\52\1\53"+
    "\5\34\1\54\1\0\1\55\7\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\2\22\1\23\1\24\12\25"+
    "\1\26\1\27\1\30\1\0\1\31\1\0\1\32\2\0"+
    "\1\33\1\0\1\34\1\35\1\22\3\25\1\36\7\25"+
    "\2\0\1\37\1\0\1\40\1\22\12\25\2\0\1\41"+
    "\1\42\1\43\2\25\1\44\1\45\3\25\1\46\1\47"+
    "\1\50\1\25\1\51\2\25\1\52\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\56\0\346\0\u0114"+
    "\0\56\0\56\0\56\0\56\0\56\0\u0142\0\56\0\u0170"+
    "\0\u019e\0\56\0\56\0\u01cc\0\56\0\u01fa\0\u0228\0\56"+
    "\0\56\0\u0256\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a"+
    "\0\u0398\0\u03c6\0\u03f4\0\u0422\0\56\0\56\0\270\0\56"+
    "\0\u0450\0\56\0\u047e\0\u04ac\0\u04da\0\u0508\0\56\0\56"+
    "\0\u0536\0\u0564\0\u0592\0\u05c0\0\u0256\0\u05ee\0\u061c\0\u064a"+
    "\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u075e\0\56\0\u078c"+
    "\0\u0508\0\u07ba\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce"+
    "\0\u08fc\0\u092a\0\u0958\0\u0986\0\u09b4\0\u09e2\0\u01fa\0\u0256"+
    "\0\u0256\0\u0a10\0\u0a3e\0\u0256\0\u0256\0\u0a6c\0\u0a9a\0\u0ac8"+
    "\0\u0256\0\56\0\u0256\0\u0af6\0\u0256\0\u0b24\0\u0b52\0\u0256"+
    "\0\u0256";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\2\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\2\1\31\3\32\1\33\1\34\1\35\1\36"+
    "\1\32\1\37\1\40\1\32\1\41\1\42\1\32\1\43"+
    "\1\32\1\44\1\45\57\0\2\3\100\0\1\46\30\0"+
    "\5\47\1\50\24\47\1\51\23\47\7\0\1\52\46\0"+
    "\10\53\1\0\21\53\1\54\23\53\16\0\1\55\56\0"+
    "\1\56\1\0\1\20\56\0\1\57\60\0\1\60\51\0"+
    "\1\26\5\0\2\26\3\0\20\26\23\0\1\26\5\0"+
    "\2\26\3\0\12\26\1\61\5\26\23\0\1\32\5\0"+
    "\2\32\3\0\20\32\23\0\1\32\5\0\2\32\3\0"+
    "\1\32\1\62\16\32\23\0\1\32\5\0\2\32\3\0"+
    "\7\32\1\63\10\32\23\0\1\32\5\0\2\32\3\0"+
    "\1\32\1\64\16\32\23\0\1\32\5\0\2\32\3\0"+
    "\5\32\1\65\10\32\1\66\1\32\23\0\1\32\5\0"+
    "\2\32\3\0\1\32\1\67\16\32\23\0\1\32\5\0"+
    "\2\32\3\0\17\32\1\70\23\0\1\32\5\0\2\32"+
    "\3\0\1\32\1\71\12\32\1\72\3\32\23\0\1\32"+
    "\5\0\2\32\3\0\4\32\1\73\13\32\23\0\1\32"+
    "\5\0\2\32\3\0\14\32\1\74\3\32\20\0\1\75"+
    "\71\0\1\76\33\0\1\77\52\0\1\53\2\0\1\53"+
    "\10\0\1\100\10\0\1\53\3\0\1\53\6\0\1\53"+
    "\2\0\1\53\1\0\1\53\3\0\2\55\2\0\52\55"+
    "\21\0\1\101\55\0\1\26\5\0\2\26\3\0\6\26"+
    "\1\102\11\26\23\0\1\32\5\0\2\32\3\0\16\32"+
    "\1\103\1\32\23\0\1\32\5\0\2\32\3\0\15\32"+
    "\1\104\2\32\23\0\1\32\5\0\2\32\3\0\7\32"+
    "\1\105\10\32\23\0\1\32\5\0\2\32\3\0\4\32"+
    "\1\106\13\32\23\0\1\32\5\0\2\32\3\0\6\32"+
    "\1\107\11\32\23\0\1\32\5\0\2\32\3\0\7\32"+
    "\1\110\10\32\23\0\1\32\5\0\2\32\3\0\14\32"+
    "\1\111\3\32\23\0\1\32\5\0\2\32\3\0\6\32"+
    "\1\112\11\32\23\0\1\32\5\0\2\32\3\0\16\32"+
    "\1\113\1\32\23\0\1\32\5\0\2\32\3\0\17\32"+
    "\1\114\2\0\16\75\1\115\37\75\2\47\2\0\52\47"+
    "\21\0\1\116\55\0\1\26\5\0\2\26\3\0\3\26"+
    "\1\117\14\26\23\0\1\32\5\0\2\32\3\0\1\32"+
    "\1\120\16\32\23\0\1\32\5\0\2\32\3\0\4\32"+
    "\1\121\13\32\23\0\1\32\5\0\2\32\3\0\15\32"+
    "\1\122\2\32\23\0\1\32\5\0\2\32\3\0\14\32"+
    "\1\123\3\32\23\0\1\32\5\0\2\32\3\0\11\32"+
    "\1\124\6\32\23\0\1\32\5\0\2\32\3\0\7\32"+
    "\1\125\10\32\23\0\1\32\5\0\2\32\3\0\1\32"+
    "\1\126\16\32\23\0\1\32\5\0\2\32\3\0\11\32"+
    "\1\127\6\32\23\0\1\32\5\0\2\32\3\0\17\32"+
    "\1\130\23\0\1\32\5\0\2\32\3\0\4\32\1\131"+
    "\13\32\2\0\55\75\1\132\21\0\1\53\55\0\1\32"+
    "\5\0\2\32\3\0\4\32\1\133\13\32\23\0\1\32"+
    "\5\0\2\32\3\0\1\32\1\134\16\32\23\0\1\32"+
    "\5\0\2\32\3\0\10\32\1\120\7\32\23\0\1\32"+
    "\5\0\2\32\3\0\16\32\1\135\1\32\23\0\1\32"+
    "\5\0\2\32\3\0\14\32\1\136\3\32\23\0\1\32"+
    "\5\0\2\32\3\0\16\32\1\137\1\32\23\0\1\32"+
    "\5\0\2\32\3\0\11\32\1\140\6\32\23\0\1\32"+
    "\5\0\2\32\3\0\4\32\1\141\13\32\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2944];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\5\11\1\1\1\11"+
    "\2\1\2\11\1\1\1\11\2\1\2\11\13\1\2\11"+
    "\1\0\1\11\1\0\1\11\2\0\1\1\1\0\2\11"+
    "\14\1\2\0\1\11\1\0\14\1\2\0\13\1\1\11"+
    "\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
private ArrayList arr;

private int toInt(String s){
    try {
        return Integer.parseInt(yytext());
    } catch (NumberFormatException e) {
        System.out.println("Erro de conversão: " + s + " para inteiro");
        return 0;
    }
}

// private float toFloat(String s){
//     try {
//         return Float.parseFloat(yytext());
//     } catch (NumberFormatException e) {
//         System.out.println("Erro de conversão: " + s + " para ponto flutuante");
//         return 0;
//     }
// }

    private float toFloat(String s){
        try {
            return Float.parseFloat(s);
        } catch (NumberFormatException e) {
            System.out.println("Erro de conversão: " + s + " para ponto flutuante");
            return 0;
        }
}


private char toChar(String s) {
   // System.out.println("Entrada recebida: " + s); // Verifique o que o lexer está recebendo
    //if (s.length() != 3 || s.charAt(0) != '\'' || s.charAt(2) != '\'') {
    if (s.charAt(0) != '\'' || s.charAt(s.length() - 1) != '\'') {
        throw new Error("Formato de caractere inválido: " + s);
    }

   String content = s.substring(1, s.length()-1);

    // Processa sequências de escape
    // Se o conteúdo começar com '\' é uma sequência de escape
    if (content.startsWith("\\")) {
        // Escape simples: deve ter exatamente 2 caracteres (ex.: '\n')
        if (content.length() == 2) {
            char esc = content.charAt(1);
            switch (esc) {
                case 'b': return '\b';   // backspace
                case 't': return '\t';   // tabulação
                case 'n': return '\n';   // quebra de linha
                case 'r': return '\r';   // carriage return
                case '\\': return '\\';  // barra invertida
                case '\'': return '\'';  // aspas simples
                case '\"': return '\"';  // aspas duplas
                default:
                    throw new Error("Sequência de escape desconhecida: " + esc);
            }
        // Escape numérico: deve ter exatamente 4 caracteres (ex.: '\065')
        } else if (content.length() == 4) {
            String digitos = content.substring(1); // Remove a barra invertida
            try {
                int code = Integer.parseInt(digitos);
                return (char) code;
            } catch (NumberFormatException e) {
                throw new Error("Código ASCII inválido: " + digitos);
            }
        } else {
            throw new Error("Escape sequence de tamanho inválido: " + content);
        }
    } else {
        // Se não for sequência de escape, deve ter exatamente um caractere
        if (content.length() != 1) {
            throw new Error("Formato de caractere inválido: " + s);
        }
        return content.charAt(0);
    }
}







private Symbol mkSymbol(int symCode, Object obj){
    return new Symbol(symCode, yyline + 1, yycolumn + 1, obj);
}

private Symbol mkSymbol(int symCode){
    return mkSymbol(symCode, null);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LangLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Symbol nextToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { return new Symbol(LangParserSym.EOF, yyline + 1, yycolumn + 1);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter ilegal <" + yytext() + ">");
            }
          // fall through
          case 44: break;
          case 2:
            { /* Ignora espaços em branco */
            }
          // fall through
          case 45: break;
          case 3:
            { return mkSymbol(LangParserSym.NOT);
            }
          // fall through
          case 46: break;
          case 4:
            { return mkSymbol(LangParserSym.MOD);
            }
          // fall through
          case 47: break;
          case 5:
            { return mkSymbol(LangParserSym.LP);
            }
          // fall through
          case 48: break;
          case 6:
            { return mkSymbol(LangParserSym.RP);
            }
          // fall through
          case 49: break;
          case 7:
            { return mkSymbol(LangParserSym.TIMES);
            }
          // fall through
          case 50: break;
          case 8:
            { return mkSymbol(LangParserSym.PLUS);
            }
          // fall through
          case 51: break;
          case 9:
            { return mkSymbol(LangParserSym.COMMA);
            }
          // fall through
          case 52: break;
          case 10:
            { return mkSymbol(LangParserSym.MINUS);
            }
          // fall through
          case 53: break;
          case 11:
            { return mkSymbol(LangParserSym.DIV);
            }
          // fall through
          case 54: break;
          case 12:
            { return mkSymbol(LangParserSym.NUMBER, toInt(yytext()));
            }
          // fall through
          case 55: break;
          case 13:
            { return mkSymbol(LangParserSym.COLON);
            }
          // fall through
          case 56: break;
          case 14:
            { return mkSymbol(LangParserSym.PV);
            }
          // fall through
          case 57: break;
          case 15:
            { return mkSymbol(LangParserSym.MENORQ);
            }
          // fall through
          case 58: break;
          case 16:
            { return mkSymbol(LangParserSym.ATTRIB);
            }
          // fall through
          case 59: break;
          case 17:
            { return mkSymbol(LangParserSym.MAIORQ);
            }
          // fall through
          case 60: break;
          case 18:
            { return mkSymbol(LangParserSym.TYID, yytext());
            }
          // fall through
          case 61: break;
          case 19:
            { return mkSymbol(LangParserSym.LBRACKET);
            }
          // fall through
          case 62: break;
          case 20:
            { return mkSymbol(LangParserSym.RBRACKET);
            }
          // fall through
          case 63: break;
          case 21:
            { return mkSymbol(LangParserSym.ID, yytext());
            }
          // fall through
          case 64: break;
          case 22:
            { return mkSymbol(LangParserSym.LBRACE);
            }
          // fall through
          case 65: break;
          case 23:
            { return mkSymbol(LangParserSym.RBRACE);
            }
          // fall through
          case 66: break;
          case 24:
            { return mkSymbol(LangParserSym.DIFERENTE);
            }
          // fall through
          case 67: break;
          case 25:
            { return mkSymbol(LangParserSym.STRING, yytext().substring(1, yytext().length() - 1));
            }
          // fall through
          case 68: break;
          case 26:
            { return mkSymbol(LangParserSym.AND);
            }
          // fall through
          case 69: break;
          case 27:
            { /* Ignora comentário de linha */
            }
          // fall through
          case 70: break;
          case 28:
            { return mkSymbol(LangParserSym.COLONCOLON);
            }
          // fall through
          case 71: break;
          case 29:
            { return mkSymbol(LangParserSym.IGUAL);
            }
          // fall through
          case 72: break;
          case 30:
            { return mkSymbol(LangParserSym.IF);
            }
          // fall through
          case 73: break;
          case 31:
            { return mkSymbol(LangParserSym.CHAR, toChar(yytext()));
            }
          // fall through
          case 74: break;
          case 32:
            { return mkSymbol(LangParserSym.FLOAT, toFloat(yytext()));
            }
          // fall through
          case 75: break;
          case 33:
            { return mkSymbol(LangParserSym.VOID);
            }
          // fall through
          case 76: break;
          case 34:
            { return mkSymbol(LangParserSym.DATA);
            }
          // fall through
          case 77: break;
          case 35:
            { return mkSymbol(LangParserSym.ELSE);
            }
          // fall through
          case 78: break;
          case 36:
            { return mkSymbol(LangParserSym.MAIN);
            }
          // fall through
          case 79: break;
          case 37:
            { return mkSymbol(LangParserSym.NULL);
            }
          // fall through
          case 80: break;
          case 38:
            { return mkSymbol(LangParserSym.TRUE, true);
            }
          // fall through
          case 81: break;
          case 39:
            { /* Ignora comentário multi-linha */
            }
          // fall through
          case 82: break;
          case 40:
            { return mkSymbol(LangParserSym.FALSE, false);
            }
          // fall through
          case 83: break;
          case 41:
            { return mkSymbol(LangParserSym.PRINT);
            }
          // fall through
          case 84: break;
          case 42:
            { return mkSymbol(LangParserSym.RETURN);
            }
          // fall through
          case 85: break;
          case 43:
            { return new Symbol(LangParserSym.ITERATE, yyline + 1, yycolumn + 1);
            }
          // fall through
          case 86: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
