
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lang.parser;

import java_cup.runtime.*;
import lang.ast.*;
import lang.ast.command.*;
import lang.ast.expr.*;
import lang.ast.types.*;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class LangParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return LangParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public LangParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public LangParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public LangParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\072\000\002\005\012\000\002\002\004\000\002\005" +
    "\011\000\002\005\010\000\002\005\003\000\002\010\007" +
    "\000\002\012\003\000\002\012\004\000\002\011\006\000" +
    "\002\013\011\000\002\013\010\000\002\013\007\000\002" +
    "\013\006\000\002\014\003\000\002\014\004\000\002\016" +
    "\003\000\002\016\005\000\002\015\005\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\004\004\000\002" +
    "\004\005\000\002\003\005\000\002\003\007\000\002\003" +
    "\011\000\002\003\007\000\002\003\011\000\002\003\004" +
    "\000\002\003\004\000\002\006\005\000\002\002\005\000" +
    "\002\002\005\000\002\002\005\000\002\002\005\000\002" +
    "\002\005\000\002\002\005\000\002\002\005\000\002\002" +
    "\005\000\002\002\005\000\002\002\005\000\002\002\004" +
    "\000\002\002\005\000\002\002\005\000\002\002\005\000" +
    "\002\002\005\000\002\002\003\000\002\002\003\000\002" +
    "\002\003\000\002\002\003\000\002\002\003\000\002\002" +
    "\003\000\002\002\003\000\002\002\003\000\002\002\007" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\012\003\007\033\005\042\004\045\010\001" +
    "\002\000\004\011\175\001\002\000\004\043\155\001\002" +
    "\000\006\042\004\045\147\001\002\000\004\002\ufffd\001" +
    "\002\000\004\011\142\001\002\000\006\042\ufff4\045\ufff4" +
    "\001\002\000\004\002\141\001\002\000\004\042\004\001" +
    "\002\000\006\042\004\045\015\001\002\000\004\011\017" +
    "\001\002\000\006\042\ufff3\045\ufff3\001\002\000\004\012" +
    "\020\001\002\000\004\013\021\001\002\000\014\032\024" +
    "\034\030\036\027\042\022\046\025\001\002\000\004\025" +
    "\137\001\002\000\016\014\136\032\024\034\030\036\027" +
    "\042\022\046\025\001\002\000\034\011\032\013\033\015" +
    "\045\024\043\037\035\040\036\041\041\042\042\044\047" +
    "\047\040\050\037\051\046\053\034\001\002\000\034\011" +
    "\032\013\033\015\045\024\043\037\035\040\036\041\041" +
    "\042\042\044\047\047\040\050\037\051\046\053\034\001" +
    "\002\000\004\026\133\001\002\000\004\011\122\001\002" +
    "\000\004\011\031\001\002\000\034\011\032\013\033\015" +
    "\045\024\043\037\035\040\036\041\041\042\042\044\047" +
    "\047\040\050\037\051\046\053\034\001\002\000\034\011" +
    "\032\013\033\015\045\024\043\037\035\040\036\041\041" +
    "\042\042\044\047\047\040\050\037\051\046\053\034\001" +
    "\002\000\034\011\032\013\033\015\045\024\043\037\035" +
    "\040\036\041\041\042\042\044\047\047\040\050\037\051" +
    "\046\053\034\001\002\000\004\042\112\001\002\000\040" +
    "\004\uffd0\005\uffd0\006\uffd0\007\uffd0\010\uffd0\012\uffd0\014" +
    "\uffd0\016\uffd0\017\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0" +
    "\026\uffd0\027\uffd0\001\002\000\040\004\uffcf\005\uffcf\006" +
    "\uffcf\007\uffcf\010\uffcf\012\uffcf\014\uffcf\016\uffcf\017\uffcf" +
    "\020\uffcf\021\uffcf\022\uffcf\023\uffcf\026\uffcf\027\uffcf\001" +
    "\002\000\040\004\uffcb\005\uffcb\006\uffcb\007\uffcb\010\uffcb" +
    "\012\uffcb\014\uffcb\016\uffcb\017\uffcb\020\uffcb\021\uffcb\022" +
    "\uffcb\023\uffcb\026\uffcb\027\uffcb\001\002\000\040\004\uffcd" +
    "\005\uffcd\006\uffcd\007\uffcd\010\uffcd\012\uffcd\014\uffcd\016" +
    "\uffcd\017\uffcd\020\uffcd\021\uffcd\022\uffcd\023\uffcd\026\uffcd" +
    "\027\uffcd\001\002\000\040\004\uffce\005\uffce\006\uffce\007" +
    "\uffce\010\uffce\012\uffce\014\uffce\016\uffce\017\uffce\020\uffce" +
    "\021\uffce\022\uffce\023\uffce\026\uffce\027\uffce\001\002\000" +
    "\040\004\uffc9\005\uffc9\006\uffc9\007\uffc9\010\uffc9\012\uffc9" +
    "\014\uffc9\016\uffc9\017\uffc9\020\uffc9\021\uffc9\022\uffc9\023" +
    "\uffc9\026\uffc9\027\uffc9\001\002\000\034\011\032\013\033" +
    "\015\045\024\043\037\035\040\036\041\041\042\042\044" +
    "\047\047\040\050\037\051\046\053\034\001\002\000\032" +
    "\004\055\005\052\006\063\007\060\010\054\012\100\017" +
    "\056\020\053\021\061\022\064\023\051\027\062\001\002" +
    "\000\034\011\032\013\033\015\045\024\043\037\035\040" +
    "\036\041\041\042\042\044\047\047\040\050\037\051\046" +
    "\053\034\001\002\000\040\004\uffca\005\uffca\006\uffca\007" +
    "\uffca\010\uffca\012\uffca\014\uffca\016\uffca\017\uffca\020\uffca" +
    "\021\uffca\022\uffca\023\uffca\026\uffca\027\uffca\001\002\000" +
    "\040\004\uffcc\005\uffcc\006\uffcc\007\uffcc\010\uffcc\012\uffcc" +
    "\014\uffcc\016\uffcc\017\uffcc\020\uffcc\021\uffcc\022\uffcc\023" +
    "\uffcc\026\uffcc\027\uffcc\001\002\000\032\004\055\005\052" +
    "\006\063\007\060\010\054\016\057\017\056\020\053\021" +
    "\061\022\064\023\051\027\062\001\002\000\034\011\032" +
    "\013\033\015\045\024\043\037\035\040\036\041\041\042" +
    "\042\044\047\047\040\050\037\051\046\053\034\001\002" +
    "\000\034\011\032\013\033\015\045\024\043\037\035\040" +
    "\036\041\041\042\042\044\047\047\040\050\037\051\046" +
    "\053\034\001\002\000\034\011\032\013\033\015\045\024" +
    "\043\037\035\040\036\041\041\042\042\044\047\047\040" +
    "\050\037\051\046\053\034\001\002\000\034\011\032\013" +
    "\033\015\045\024\043\037\035\040\036\041\041\042\042" +
    "\044\047\047\040\050\037\051\046\053\034\001\002\000" +
    "\034\011\032\013\033\015\045\024\043\037\035\040\036" +
    "\041\041\042\042\044\047\047\040\050\037\051\046\053" +
    "\034\001\002\000\034\011\032\013\033\015\045\024\043" +
    "\037\035\040\036\041\041\042\042\044\047\047\040\050" +
    "\037\051\046\053\034\001\002\000\040\004\uffd2\005\uffd2" +
    "\006\uffd2\007\uffd2\010\uffd2\012\uffd2\014\uffd2\016\uffd2\017" +
    "\uffd2\020\uffd2\021\uffd2\022\uffd2\023\uffd2\026\uffd2\027\uffd2" +
    "\001\002\000\034\011\032\013\033\015\045\024\043\037" +
    "\035\040\036\041\041\042\042\044\047\047\040\050\037" +
    "\051\046\053\034\001\002\000\034\011\032\013\033\015" +
    "\045\024\043\037\035\040\036\041\041\042\042\044\047" +
    "\047\040\050\037\051\046\053\034\001\002\000\034\011" +
    "\032\013\033\015\045\024\043\037\035\040\036\041\041" +
    "\042\042\044\047\047\040\050\037\051\046\053\034\001" +
    "\002\000\034\011\032\013\033\015\045\024\043\037\035" +
    "\040\036\041\041\042\042\044\047\047\040\050\037\051" +
    "\046\053\034\001\002\000\034\011\032\013\033\015\045" +
    "\024\043\037\035\040\036\041\041\042\042\044\047\047" +
    "\040\050\037\051\046\053\034\001\002\000\040\004\055" +
    "\005\052\006\063\007\060\010\054\012\uffd7\014\uffd7\016" +
    "\uffd7\017\056\020\053\021\uffd7\022\uffd7\023\uffd7\026\uffd7" +
    "\027\uffd7\001\002\000\040\004\uffdd\005\uffdd\006\uffdd\007" +
    "\uffdd\010\uffdd\012\uffdd\014\uffdd\016\uffdd\017\uffdd\020\uffdd" +
    "\021\uffdd\022\uffdd\023\uffdd\026\uffdd\027\uffdd\001\002\000" +
    "\040\004\055\005\052\006\063\007\060\010\054\012\uffd1" +
    "\014\uffd1\016\uffd1\017\056\020\053\021\061\022\064\023" +
    "\051\026\uffd1\027\uffd1\001\002\000\040\004\055\005\052" +
    "\006\063\007\060\010\054\012\uffd8\014\uffd8\016\uffd8\017" +
    "\056\020\053\021\uffd8\022\uffd8\023\uffd8\026\uffd8\027\uffd8" +
    "\001\002\000\040\004\uffdc\005\uffdc\006\uffdc\007\uffdc\010" +
    "\uffdc\012\uffdc\014\uffdc\016\uffdc\017\uffdc\020\uffdc\021\uffdc" +
    "\022\uffdc\023\uffdc\026\uffdc\027\uffdc\001\002\000\040\004" +
    "\055\005\052\006\063\007\060\010\054\012\uffda\014\uffda" +
    "\016\uffda\017\uffda\020\uffda\021\uffda\022\uffda\023\uffda\026" +
    "\uffda\027\uffda\001\002\000\040\004\uffdf\005\uffdf\006\063" +
    "\007\060\010\054\012\uffdf\014\uffdf\016\uffdf\017\uffdf\020" +
    "\uffdf\021\uffdf\022\uffdf\023\uffdf\026\uffdf\027\uffdf\001\002" +
    "\000\040\004\uffdb\005\uffdb\006\uffdb\007\uffdb\010\uffdb\012" +
    "\uffdb\014\uffdb\016\uffdb\017\uffdb\020\uffdb\021\uffdb\022\uffdb" +
    "\023\uffdb\026\uffdb\027\uffdb\001\002\000\040\004\055\005" +
    "\052\006\063\007\060\010\054\012\uffd9\014\uffd9\016\uffd9" +
    "\017\uffd9\020\uffd9\021\uffd9\022\uffd9\023\uffd9\026\uffd9\027" +
    "\uffd9\001\002\000\040\004\uffde\005\uffde\006\063\007\060" +
    "\010\054\012\uffde\014\uffde\016\uffde\017\uffde\020\uffde\021" +
    "\uffde\022\uffde\023\uffde\026\uffde\027\uffde\001\002\000\040" +
    "\004\055\005\052\006\063\007\060\010\054\012\uffd6\014" +
    "\uffd6\016\uffd6\017\056\020\053\021\061\022\064\023\uffd6" +
    "\026\uffd6\027\uffd6\001\002\000\004\013\101\001\002\000" +
    "\014\032\024\034\030\036\027\042\022\046\025\001\002" +
    "\000\006\026\uffe6\035\103\001\002\000\004\013\101\001" +
    "\002\000\004\026\uffe5\001\002\000\016\014\106\032\024" +
    "\034\030\036\027\042\022\046\025\001\002\000\012\026" +
    "\uffe0\035\uffe0\042\uffe0\045\uffe0\001\002\000\004\026\110" +
    "\001\002\000\016\014\uffe8\032\uffe8\034\uffe8\036\uffe8\042" +
    "\uffe8\046\uffe8\001\002\000\040\004\uffd5\005\uffd5\006\uffd5" +
    "\007\uffd5\010\uffd5\012\uffd5\014\uffd5\016\uffd5\017\uffd5\020" +
    "\uffd5\021\uffd5\022\uffd5\023\uffd5\026\uffd5\027\uffd5\001\002" +
    "\000\004\015\113\001\002\000\034\011\032\013\033\015" +
    "\045\024\043\037\035\040\036\041\041\042\042\044\047" +
    "\047\040\050\037\051\046\053\034\001\002\000\032\004" +
    "\055\005\052\006\063\007\060\010\054\016\115\017\056" +
    "\020\053\021\061\022\064\023\051\027\062\001\002\000" +
    "\040\004\uffc8\005\uffc8\006\uffc8\007\uffc8\010\uffc8\012\uffc8" +
    "\014\uffc8\016\uffc8\017\uffc8\020\uffc8\021\uffc8\022\uffc8\023" +
    "\uffc8\026\uffc8\027\uffc8\001\002\000\032\004\055\005\052" +
    "\006\063\007\060\010\054\014\117\017\056\020\053\021" +
    "\061\022\064\023\051\027\062\001\002\000\040\004\uffd3" +
    "\005\uffd3\006\uffd3\007\uffd3\010\uffd3\012\uffd3\014\uffd3\016" +
    "\uffd3\017\uffd3\020\uffd3\021\uffd3\022\uffd3\023\uffd3\026\uffd3" +
    "\027\uffd3\001\002\000\032\004\055\005\052\006\063\007" +
    "\060\010\054\012\121\017\056\020\053\021\061\022\064" +
    "\023\051\027\062\001\002\000\040\004\uffd4\005\uffd4\006" +
    "\uffd4\007\uffd4\010\uffd4\012\uffd4\014\uffd4\016\uffd4\017\uffd4" +
    "\020\uffd4\021\uffd4\022\uffd4\023\uffd4\026\uffd4\027\uffd4\001" +
    "\002\000\034\011\032\013\033\015\045\024\043\037\035" +
    "\040\036\041\041\042\123\044\047\047\040\050\037\051" +
    "\046\053\034\001\002\000\034\004\uffc9\005\uffc9\006\uffc9" +
    "\007\uffc9\010\uffc9\012\uffc9\017\uffc9\020\uffc9\021\uffc9\022" +
    "\uffc9\023\uffc9\027\uffc9\030\127\001\002\000\032\004\055" +
    "\005\052\006\063\007\060\010\054\012\125\017\056\020" +
    "\053\021\061\022\064\023\051\027\062\001\002\000\004" +
    "\013\101\001\002\000\004\026\uffe4\001\002\000\034\011" +
    "\032\013\033\015\045\024\043\037\035\040\036\041\041" +
    "\042\042\044\047\047\040\050\037\051\046\053\034\001" +
    "\002\000\032\004\055\005\052\006\063\007\060\010\054" +
    "\012\131\017\056\020\053\021\061\022\064\023\051\027" +
    "\062\001\002\000\004\013\101\001\002\000\004\026\uffe3" +
    "\001\002\000\016\014\uffe9\032\uffe9\034\uffe9\036\uffe9\042" +
    "\uffe9\046\uffe9\001\002\000\032\004\055\005\052\006\063" +
    "\007\060\010\054\017\056\020\053\021\061\022\064\023" +
    "\051\026\uffe2\027\062\001\002\000\032\004\055\005\052" +
    "\006\063\007\060\010\054\017\056\020\053\021\061\022" +
    "\064\023\051\026\uffe1\027\062\001\002\000\004\002\001" +
    "\001\002\000\034\011\032\013\033\015\045\024\043\037" +
    "\035\040\036\041\041\042\042\044\047\047\040\050\037" +
    "\051\046\053\034\001\002\000\032\004\055\005\052\006" +
    "\063\007\060\010\054\017\056\020\053\021\061\022\064" +
    "\023\051\026\uffe7\027\062\001\002\000\004\002\000\001" +
    "\002\000\004\012\143\001\002\000\004\013\144\001\002" +
    "\000\014\032\024\034\030\036\027\042\022\046\025\001" +
    "\002\000\016\014\146\032\024\034\030\036\027\042\022" +
    "\046\025\001\002\000\004\002\ufffe\001\002\000\004\011" +
    "\150\001\002\000\004\012\151\001\002\000\004\013\152" +
    "\001\002\000\014\032\024\034\030\036\027\042\022\046" +
    "\025\001\002\000\016\014\154\032\024\034\030\036\027" +
    "\042\022\046\025\001\002\000\004\002\uffff\001\002\000" +
    "\004\013\156\001\002\000\004\042\157\001\002\000\004" +
    "\031\164\001\002\000\006\014\ufffb\042\ufffb\001\002\000" +
    "\006\014\163\042\157\001\002\000\006\014\ufffa\042\ufffa" +
    "\001\002\000\004\042\ufffc\001\002\000\016\037\167\042" +
    "\165\043\170\044\173\051\171\052\172\001\002\000\012" +
    "\012\uffec\013\uffec\026\uffec\027\uffec\001\002\000\004\026" +
    "\174\001\002\000\012\012\uffed\013\uffed\026\uffed\027\uffed" +
    "\001\002\000\012\012\uffea\013\uffea\026\uffea\027\uffea\001" +
    "\002\000\012\012\uffeb\013\uffeb\026\uffeb\027\uffeb\001\002" +
    "\000\012\012\uffef\013\uffef\026\uffef\027\uffef\001\002\000" +
    "\012\012\uffee\013\uffee\026\uffee\027\uffee\001\002\000\006" +
    "\014\ufff9\042\ufff9\001\002\000\006\012\177\042\176\001" +
    "\002\000\004\031\215\001\002\000\006\013\101\030\211" +
    "\001\002\000\006\012\ufff2\027\ufff2\001\002\000\006\012" +
    "\203\027\202\001\002\000\004\042\176\001\002\000\006" +
    "\013\101\030\204\001\002\000\016\037\167\042\165\043" +
    "\170\044\173\051\171\052\172\001\002\000\006\042\ufff6" +
    "\045\ufff6\001\002\000\004\013\101\001\002\000\006\042" +
    "\ufff8\045\ufff8\001\002\000\006\012\ufff1\027\ufff1\001\002" +
    "\000\016\037\167\042\165\043\170\044\173\051\171\052" +
    "\172\001\002\000\006\042\ufff5\045\ufff5\001\002\000\004" +
    "\013\101\001\002\000\006\042\ufff7\045\ufff7\001\002\000" +
    "\016\037\167\042\165\043\170\044\173\051\171\052\172" +
    "\001\002\000\006\012\ufff0\027\ufff0\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\012\005\011\010\012\013\010\014\005\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\013\015" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\013\010\014\013\001\001" +
    "\000\004\013\015\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\003\025" +
    "\004\022\001\001\000\002\001\001\000\004\003\106\001" +
    "\001\000\004\002\134\001\001\000\004\002\133\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\002\043\001\001\000\004\002\117\001\001\000\004" +
    "\002\115\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\002\110\001\001\000" +
    "\002\001\001\000\004\002\047\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\002\076\001" +
    "\001\000\004\002\075\001\001\000\004\002\074\001\001" +
    "\000\004\002\073\001\001\000\004\002\072\001\001\000" +
    "\004\002\071\001\001\000\002\001\001\000\004\002\070" +
    "\001\001\000\004\002\067\001\001\000\004\002\066\001" +
    "\001\000\004\002\065\001\001\000\004\002\064\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\101\001\001\000\006" +
    "\003\025\004\104\001\001\000\002\001\001\000\004\006" +
    "\103\001\001\000\002\001\001\000\004\003\106\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\002\113\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\002\123\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\125\001\001\000\002\001\001\000\004\002\127" +
    "\001\001\000\002\001\001\000\004\006\131\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\002\137\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\003\025\004\144\001\001\000\004\003" +
    "\106\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\003\025\004\152\001" +
    "\001\000\004\003\106\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\011\157\012\160\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\161\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\007\165\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\015\177\016\200\001\001" +
    "\000\002\001\001\000\004\006\211\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\015\207\001\001\000\004" +
    "\006\204\001\001\000\004\007\205\001\001\000\002\001" +
    "\001\000\004\006\206\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\212\001\001\000\002\001\001\000" +
    "\004\006\213\001\001\000\002\001\001\000\004\007\215" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$LangParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$LangParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$LangParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 
    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.nextToken(); 
    }


// Conecta o parser ao lexer
LangLexer s;
public LangParser(LangLexer s){ this.s = s; }
// Obtém a linha atual


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$LangParser$actions {
  private final LangParser parser;

  /** Constructor */
  CUP$LangParser$actions(LangParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$LangParser$do_action_part00000000(
    int                        CUP$LangParser$act_num,
    java_cup.runtime.lr_parser CUP$LangParser$parser,
    java.util.Stack            CUP$LangParser$stack,
    int                        CUP$LangParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$LangParser$result;

      /* select the action based on the action number */
      switch (CUP$LangParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // prog ::= dataDecl funcs MAIN LP RP LBRACE cmds RBRACE 
            {
              Cmd RESULT =null;
		int dataleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-7)).left;
		int dataright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-7)).right;
		DataDecl data = (DataDecl)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-7)).value;
		int funcsleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).left;
		int funcsright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).right;
		List<Func> funcs = (List<Func>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		List<Cmd> c = (List<Cmd>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
    List<DataDecl> dataList = new ArrayList<>();
    dataList.add(data);
    RESULT = new MainBlock(dataList, funcs, c);

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("prog",3, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-7)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Cmd start_val = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		RESULT = start_val;
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$LangParser$parser.done_parsing();
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // prog ::= funcs MAIN LP RP LBRACE cmds RBRACE 
            {
              Cmd RESULT =null;
		int funcsleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).left;
		int funcsright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).right;
		List<Func> funcs = (List<Func>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		List<Cmd> c = (List<Cmd>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
    RESULT = new MainBlock(new ArrayList<>(), funcs, c);

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("prog",3, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // prog ::= MAIN LP RP LBRACE cmds RBRACE 
            {
              Cmd RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		List<Cmd> c = (List<Cmd>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
    RESULT = new MainBlock(new ArrayList<>(), new ArrayList<>(), c);

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("prog",3, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-5)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // prog ::= error 
            {
              Cmd RESULT =null;
		 
            System.err.println("Erro de sintaxe!"); 
            RESULT = null; 
        
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("prog",3, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // dataDecl ::= DATA TYID LBRACE decls RBRACE 
            {
              DataDecl RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).value;
		int dsleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int dsright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		List<Decl> ds = (List<Decl>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
    RESULT = new DataDecl(ileft, iright, i, ds);

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("dataDecl",6, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // decls ::= decl 
            {
              List<Decl> RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Decl d = (Decl)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    List<Decl> list = new ArrayList<>();
    list.add(d);
    RESULT = list;

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("decls",8, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // decls ::= decls decl 
            {
              List<Decl> RESULT =null;
		int dsleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int dsright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		List<Decl> ds = (List<Decl>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Decl d = (Decl)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    ds.add(d);
    RESULT = ds;

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("decls",8, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // decl ::= ID COLONCOLON type PV 
            {
              Decl RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		LType t = (LType)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
    RESULT = new Decl(ileft, iright, i, t);

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("decl",7, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // func ::= ID LP params RP COLON type stmtBlock 
            {
              Func RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).right;
		List<Param> p = (List<Param>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		LType t = (LType)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Cmd b = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    RESULT = new Func(ileft, iright, i, p, t, List.of(b));

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("func",9, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // func ::= ID LP RP COLON type stmtBlock 
            {
              Func RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-5)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-5)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		LType t = (LType)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Cmd b = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    RESULT = new Func(ileft, iright, i, new ArrayList<>(), t, List.of(b));

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("func",9, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-5)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // func ::= ID LP params RP stmtBlock 
            {
              Func RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		List<Param> p = (List<Param>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Cmd b = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    RESULT = new Func(ileft, iright, i, p, null, List.of(b));

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("func",9, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // func ::= ID LP RP stmtBlock 
            {
              Func RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Cmd b = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    RESULT = new Func(ileft, iright, i, new ArrayList<>(), null, List.of(b));

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("func",9, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // funcs ::= func 
            {
              List<Func> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Func f = (Func)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 
            List<Func> list = new ArrayList<>(); 
            list.add(f); 
            RESULT = list; 
          
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("funcs",10, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // funcs ::= funcs func 
            {
              List<Func> RESULT =null;
		int fsleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int fsright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		List<Func> fs = (List<Func>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Func f = (Func)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 
            fs.add(f); 
            RESULT = fs; 
          
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("funcs",10, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // params ::= param 
            {
              List<Param> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Param p = (Param)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    List<Param> list = new ArrayList<>();
    list.add(p);
    RESULT = list;

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("params",12, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // params ::= params COMMA param 
            {
              List<Param> RESULT =null;
		int psleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int psright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		List<Param> ps = (List<Param>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Param p = (Param)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    ps.add(p);
    RESULT = ps;

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("params",12, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // param ::= ID COLONCOLON type 
            {
              Param RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		LType t = (LType)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
    RESULT = new Param(ileft, iright, i, t);

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("param",11, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // type ::= VOID 
            {
              LType RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new TyVoid(ileft, iright); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // type ::= CHAR 
            {
              LType RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Character i = (Character)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new TyChar(ileft, iright); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // type ::= NUMBER 
            {
              LType RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new TyInt(ileft, iright); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // type ::= ID 
            {
              LType RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new UserType(ileft, iright, i); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // type ::= FLOAT 
            {
              LType RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Float i = (Float)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new TyFloat(ileft, iright); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // type ::= TYID 
            {
              LType RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new UserType(ileft, iright, i); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // cmds ::= cmd PV 
            {
              List<Cmd> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Cmd c = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
    List<Cmd> list = new ArrayList<>();
    list.add(c);
    RESULT = list;

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmds",2, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // cmds ::= cmds cmd PV 
            {
              List<Cmd> RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		List<Cmd> cs = (List<Cmd>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Cmd c = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
    cs.add(c);
    RESULT = cs;

              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmds",2, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // cmd ::= ID ATTRIB expr 
            {
              Cmd RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
        RESULT = new Attrib(ileft, iright, new Var(ileft, iright, i), e);
      
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmd",1, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // cmd ::= IF LP expr RP stmtBlock 
            {
              Cmd RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Cmd s = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
        RESULT = new IfCmd(e, s, null); 
      
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmd",1, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // cmd ::= IF LP expr RP stmtBlock ELSE stmtBlock 
            {
              Cmd RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Cmd s1 = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Cmd s2 = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
        RESULT = new IfCmd(e, s1, s2); 
      
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmd",1, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // cmd ::= ITERATE LP expr RP stmtBlock 
            {
              Cmd RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Cmd s = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
        if (e instanceof ArrayInit || e instanceof Var) {
            RESULT = new IterateCmd(e, s); 
        } else {
            RESULT = new IterateCmd(e, s); 
        }
      
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmd",1, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // cmd ::= ITERATE LP ID COLON expr RP stmtBlock 
            {
              Cmd RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Cmd s = (Cmd)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		
        RESULT = new IterateCmdWithVar(ileft, iright, new Var(ileft, iright, i), e, s);
      
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmd",1, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-6)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // cmd ::= RETURN expr 
            {
              Cmd RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 
        RESULT = new ReturnExpr(e); 
      
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmd",1, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // cmd ::= PRINT expr 
            {
              Cmd RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 
        RESULT = new Print(e); 
      
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("cmd",1, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // stmtBlock ::= LBRACE cmds RBRACE 
            {
              Cmd RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		List<Cmd> cs = (List<Cmd>)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
                RESULT = new MainBlock(new ArrayList<>(), new ArrayList<>(), cs);
              
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("stmtBlock",4, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= expr PLUS expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Plus(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= expr MINUS expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Minus(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= expr TIMES expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Times(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= expr DIV expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Div(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= expr MOD expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Mod(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr MENORQ expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new MenorQ(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr MAIORQ expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new MaiorQ(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= expr IGUAL expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Igual(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= expr DIFERENTE expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Diferente(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr AND expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new And(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= NOT expr 
            {
              Exp RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Not(sleft, sright, e); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= LP expr RP 
            {
              Exp RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		 RESULT = e; 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= LBRACE expr RBRACE 
            {
              Exp RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		 RESULT = e; 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= LBRACKET expr RBRACKET 
            {
              Exp RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Exp e = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		 RESULT = e; 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr COMMA expr 
            {
              Exp RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).right;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Comma(sleft, sright, e1, e2); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-2)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= NUMBER 
            {
              Exp RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new IntLit(ileft, iright, i); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= TRUE 
            {
              Exp RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Boolean i = (Boolean)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new BoolLit(ileft, iright, i); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= FALSE 
            {
              Exp RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Boolean i = (Boolean)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new BoolLit(ileft, iright, i); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= STRING 
            {
              Exp RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new StringLit(sleft, sright, s); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= CHAR 
            {
              Exp RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Character c = (Character)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new CharLit(cleft, cright, c); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= NULL 
            {
              Exp RESULT =null;
		 RESULT = new NullLit(0, 0); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= FLOAT 
            {
              Exp RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		Float f = (Float)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new FloatLit(fleft, fright, f); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= ID 
            {
              Exp RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.peek()).value;
		 RESULT = new Var(ileft, iright, i); 
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= NEW ID LBRACKET expr RBRACKET 
            {
              Exp RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-3)).value;
		int sizeleft = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).left;
		int sizeright = ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).right;
		Exp size = (Exp)((java_cup.runtime.Symbol) CUP$LangParser$stack.elementAt(CUP$LangParser$top-1)).value;
		
          RESULT = new ArrayInit(new UserType(ileft, iright, i), size);
        
              CUP$LangParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$LangParser$stack.elementAt(CUP$LangParser$top-4)), ((java_cup.runtime.Symbol)CUP$LangParser$stack.peek()), RESULT);
            }
          return CUP$LangParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$LangParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$LangParser$do_action(
    int                        CUP$LangParser$act_num,
    java_cup.runtime.lr_parser CUP$LangParser$parser,
    java.util.Stack            CUP$LangParser$stack,
    int                        CUP$LangParser$top)
    throws java.lang.Exception
    {
              return CUP$LangParser$do_action_part00000000(
                               CUP$LangParser$act_num,
                               CUP$LangParser$parser,
                               CUP$LangParser$stack,
                               CUP$LangParser$top);
    }
}

}
